/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.opentech.acsemv3dsProxyApiClient.api;

import com.opentech.acsemv3dsProxyApiClient.model.CheckAuthResultWebRequest;
import com.opentech.acsemv3dsProxyApiClient.model.CheckAuthResultWebResponse;
import com.opentech.acsemv3dsProxyApiClient.model.EvaluateAuthenticationWebRequest;
import com.opentech.acsemv3dsProxyApiClient.model.EvaluateAuthenticationWebResponse;
import com.opentech.acsemv3dsProxyApiClient.model.EvaluateChallengeStepAuthenticatorWebRequest;
import com.opentech.acsemv3dsProxyApiClient.model.EvaluateChallengeStepAuthenticatorWebResponse;
import com.opentech.acsemv3dsProxyApiClient.model.InitChallengeAuthenticatorWebRequest;
import com.opentech.acsemv3dsProxyApiClient.model.InitChallengeAuthenticatorWebResponse;
import com.opentech.acsemv3dsProxyApiClient.model.PerformDecoupledAuthWebRequest;
import com.opentech.acsemv3dsProxyApiClient.model.PerformDecoupledAuthWebResponse;
import com.opentech.acsemv3dsProxyApiClient.model.PrepareAuthenticationCompletionWebRequest;
import com.opentech.acsemv3dsProxyApiClient.model.PrepareAuthenticationCompletionWebResponse;
import com.opentech.acsemv3dsProxyApiClient.model.ResendChallengeWebRequest;
import com.opentech.acsemv3dsProxyApiClient.model.ResendChallengeWebResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AuthenticatorControllerApi
 */
@Ignore
public class AuthenticatorControllerApiTest {

    private final AuthenticatorControllerApi api = new AuthenticatorControllerApi();

    /**
     * checkAuthResult
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void checkAuthResultUsingPOSTTest() {
        CheckAuthResultWebRequest body = null;
        String issuerCode = null;
        CheckAuthResultWebResponse response = api.checkAuthResultUsingPOST(body, issuerCode);

        // TODO: test validations
    }
    /**
     * evaluateAuthentication
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void evaluateAuthenticationUsingPOSTTest() {
        EvaluateAuthenticationWebRequest body = null;
        String issuerCode = null;
        EvaluateAuthenticationWebResponse response = api.evaluateAuthenticationUsingPOST(body, issuerCode);

        // TODO: test validations
    }
    /**
     * evaluateChallengeStep
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void evaluateChallengeStepUsingPOSTTest() {
        EvaluateChallengeStepAuthenticatorWebRequest body = null;
        String issuerCode = null;
        EvaluateChallengeStepAuthenticatorWebResponse response = api.evaluateChallengeStepUsingPOST(body, issuerCode);

        // TODO: test validations
    }
    /**
     * initChallenge
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void initChallengeUsingPOSTTest() {
        InitChallengeAuthenticatorWebRequest body = null;
        String issuerCode = null;
        InitChallengeAuthenticatorWebResponse response = api.initChallengeUsingPOST(body, issuerCode);

        // TODO: test validations
    }
    /**
     * performDecoupledAuthentication
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void performDecoupledAuthenticationUsingPOSTTest() {
        PerformDecoupledAuthWebRequest body = null;
        String issuerCode = null;
        PerformDecoupledAuthWebResponse response = api.performDecoupledAuthenticationUsingPOST(body, issuerCode);

        // TODO: test validations
    }
    /**
     * prepareAuthenticationCompletion
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void prepareAuthenticationCompletionUsingPOSTTest() {
        PrepareAuthenticationCompletionWebRequest body = null;
        String issuerCode = null;
        PrepareAuthenticationCompletionWebResponse response = api.prepareAuthenticationCompletionUsingPOST(body, issuerCode);

        // TODO: test validations
    }
    /**
     * resendChallenge
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void resendChallengeUsingPOSTTest() {
        ResendChallengeWebRequest body = null;
        String issuerCode = null;
        ResendChallengeWebResponse response = api.resendChallengeUsingPOST(body, issuerCode);

        // TODO: test validations
    }
}
