/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.opentech.acsemv3dsProxyApiClient.api;

import com.opentech.acsemv3dsProxyApiClient.model.DetokenizeWebRequest;
import com.opentech.acsemv3dsProxyApiClient.model.DetokenizeWebResponse;
import com.opentech.acsemv3dsProxyApiClient.model.TokenizeWebRequest;
import com.opentech.acsemv3dsProxyApiClient.model.TokenizeWebResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CardTokenizerControllerApi
 */
@Ignore
public class CardTokenizerControllerApiTest {

    private final CardTokenizerControllerApi api = new CardTokenizerControllerApi();

    /**
     * detokenize
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void detokenizeUsingPOSTTest() {
        DetokenizeWebRequest body = null;
        String issuerCode = null;
        DetokenizeWebResponse response = api.detokenizeUsingPOST(body, issuerCode);

        // TODO: test validations
    }
    /**
     * tokenize
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void tokenizeUsingPOSTTest() {
        TokenizeWebRequest body = null;
        String issuerCode = null;
        TokenizeWebResponse response = api.tokenizeUsingPOST(body, issuerCode);

        // TODO: test validations
    }
}
