/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.opentech.acsemv3dsProxyApiClient.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.opentech.acsemv3dsProxyApiClient.model.Extension;
import com.opentech.acsemv3dsProxyApiClient.model.Phone;
import com.opentech.acsemv3dsProxyApiClient.model.SdkEphemPubKey;
import com.opentech.acsemv3dsProxyApiClient.model.ThreeDSCardholderAccountInfo;
import com.opentech.acsemv3dsProxyApiClient.model.ThreeDSMerchantRiskIndicator;
import com.opentech.acsemv3dsProxyApiClient.model.ThreeDSRequestorAuthInfo;
import com.opentech.acsemv3dsProxyApiClient.model.ThreeDSRequestorPriorAuthInfo;
import com.opentech.acsemv3dsProxyApiClient.model.ThreeDSSdkRenderingOptions;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * AReq
 */

public class AReq {
  @JsonProperty("acctID")
  private String acctID = null;

  @JsonProperty("acctInfo")
  private ThreeDSCardholderAccountInfo acctInfo = null;

  @JsonProperty("acctNumber")
  private String acctNumber = null;

  @JsonProperty("acctType")
  private String acctType = null;

  @JsonProperty("acquirerBIN")
  private String acquirerBIN = null;

  @JsonProperty("acquirerMerchantID")
  private String acquirerMerchantID = null;

  @JsonProperty("addrMatch")
  private String addrMatch = null;

  @JsonProperty("billAddrCity")
  private String billAddrCity = null;

  @JsonProperty("billAddrCountry")
  private String billAddrCountry = null;

  @JsonProperty("billAddrLine1")
  private String billAddrLine1 = null;

  @JsonProperty("billAddrLine2")
  private String billAddrLine2 = null;

  @JsonProperty("billAddrLine3")
  private String billAddrLine3 = null;

  @JsonProperty("billAddrPostCode")
  private String billAddrPostCode = null;

  @JsonProperty("billAddrState")
  private String billAddrState = null;

  @JsonProperty("broadInfo")
  private Object broadInfo = null;

  @JsonProperty("browserAcceptHeader")
  private String browserAcceptHeader = null;

  @JsonProperty("browserColorDepth")
  private String browserColorDepth = null;

  @JsonProperty("browserIP")
  private String browserIP = null;

  @JsonProperty("browserJavaEnabled")
  private Boolean browserJavaEnabled = null;

  @JsonProperty("browserJavascriptEnabled")
  private Boolean browserJavascriptEnabled = null;

  @JsonProperty("browserLanguage")
  private String browserLanguage = null;

  @JsonProperty("browserScreenHeight")
  private String browserScreenHeight = null;

  @JsonProperty("browserScreenWidth")
  private String browserScreenWidth = null;

  @JsonProperty("browserTZ")
  private String browserTZ = null;

  @JsonProperty("browserUserAgent")
  private String browserUserAgent = null;

  @JsonProperty("cardExpiryDate")
  private String cardExpiryDate = null;

  @JsonProperty("cardholderName")
  private String cardholderName = null;

  @JsonProperty("deviceChannel")
  private String deviceChannel = null;

  @JsonProperty("deviceInfo")
  private Object deviceInfo = null;

  @JsonProperty("deviceRenderOptions")
  private ThreeDSSdkRenderingOptions deviceRenderOptions = null;

  @JsonProperty("dsReferenceNumber")
  private String dsReferenceNumber = null;

  @JsonProperty("dsTransID")
  private String dsTransID = null;

  @JsonProperty("dsURL")
  private String dsURL = null;

  @JsonProperty("email")
  private String email = null;

  @JsonProperty("homePhone")
  private Phone homePhone = null;

  @JsonProperty("mcc")
  private String mcc = null;

  @JsonProperty("merchantCountryCode")
  private String merchantCountryCode = null;

  @JsonProperty("merchantName")
  private String merchantName = null;

  @JsonProperty("merchantRiskIndicator")
  private ThreeDSMerchantRiskIndicator merchantRiskIndicator = null;

  @JsonProperty("messageCategory")
  private String messageCategory = null;

  @JsonProperty("messageExtension")
  private List<Extension> messageExtension = null;

  @JsonProperty("mobilePhone")
  private Phone mobilePhone = null;

  @JsonProperty("notificationURL")
  private String notificationURL = null;

  @JsonProperty("payTokenInd")
  private Boolean payTokenInd = null;

  @JsonProperty("payTokenSource")
  private String payTokenSource = null;

  @JsonProperty("purchaseAmount")
  private String purchaseAmount = null;

  @JsonProperty("purchaseCurrency")
  private String purchaseCurrency = null;

  @JsonProperty("purchaseDate")
  private String purchaseDate = null;

  @JsonProperty("purchaseExponent")
  private String purchaseExponent = null;

  @JsonProperty("purchaseInstalData")
  private String purchaseInstalData = null;

  @JsonProperty("recurringExpiry")
  private String recurringExpiry = null;

  @JsonProperty("recurringFrequency")
  private String recurringFrequency = null;

  @JsonProperty("sdkAppID")
  private String sdkAppID = null;

  @JsonProperty("sdkEncData")
  private String sdkEncData = null;

  @JsonProperty("sdkEphemPubKey")
  private SdkEphemPubKey sdkEphemPubKey = null;

  @JsonProperty("sdkMaxTimeout")
  private String sdkMaxTimeout = null;

  @JsonProperty("sdkReferenceNumber")
  private String sdkReferenceNumber = null;

  @JsonProperty("sdkTransID")
  private String sdkTransID = null;

  @JsonProperty("shipAddrCity")
  private String shipAddrCity = null;

  @JsonProperty("shipAddrCountry")
  private String shipAddrCountry = null;

  @JsonProperty("shipAddrLine1")
  private String shipAddrLine1 = null;

  @JsonProperty("shipAddrLine2")
  private String shipAddrLine2 = null;

  @JsonProperty("shipAddrLine3")
  private String shipAddrLine3 = null;

  @JsonProperty("shipAddrPostCode")
  private String shipAddrPostCode = null;

  @JsonProperty("shipAddrState")
  private String shipAddrState = null;

  @JsonProperty("threeDSCompInd")
  private String threeDSCompInd = null;

  @JsonProperty("threeDSReqAuthMethodInd")
  private String threeDSReqAuthMethodInd = null;

  @JsonProperty("threeDSRequestorAuthenticationInd")
  private String threeDSRequestorAuthenticationInd = null;

  @JsonProperty("threeDSRequestorAuthenticationInfo")
  private ThreeDSRequestorAuthInfo threeDSRequestorAuthenticationInfo = null;

  @JsonProperty("threeDSRequestorChallengeInd")
  private String threeDSRequestorChallengeInd = null;

  @JsonProperty("threeDSRequestorDecMaxTime")
  private String threeDSRequestorDecMaxTime = null;

  @JsonProperty("threeDSRequestorDecReqInd")
  private String threeDSRequestorDecReqInd = null;

  @JsonProperty("threeDSRequestorID")
  private String threeDSRequestorID = null;

  @JsonProperty("threeDSRequestorName")
  private String threeDSRequestorName = null;

  @JsonProperty("threeDSRequestorPriorAuthenticationInfo")
  private ThreeDSRequestorPriorAuthInfo threeDSRequestorPriorAuthenticationInfo = null;

  @JsonProperty("threeDSRequestorURL")
  private String threeDSRequestorURL = null;

  @JsonProperty("threeDSServerOperatorID")
  private String threeDSServerOperatorID = null;

  @JsonProperty("threeDSServerRefNumber")
  private String threeDSServerRefNumber = null;

  @JsonProperty("threeDSServerTransID")
  private String threeDSServerTransID = null;

  @JsonProperty("threeDSServerURL")
  private String threeDSServerURL = null;

  @JsonProperty("threeRIInd")
  private String threeRIInd = null;

  @JsonProperty("transType")
  private String transType = null;

  @JsonProperty("whiteListStatus")
  private String whiteListStatus = null;

  @JsonProperty("whiteListStatusSource")
  private String whiteListStatusSource = null;

  @JsonProperty("workPhone")
  private Phone workPhone = null;

  public AReq acctID(String acctID) {
    this.acctID = acctID;
    return this;
  }

   /**
   * Get acctID
   * @return acctID
  **/
  @ApiModelProperty(value = "")
  public String getAcctID() {
    return acctID;
  }

  public void setAcctID(String acctID) {
    this.acctID = acctID;
  }

  public AReq acctInfo(ThreeDSCardholderAccountInfo acctInfo) {
    this.acctInfo = acctInfo;
    return this;
  }

   /**
   * Get acctInfo
   * @return acctInfo
  **/
  @ApiModelProperty(value = "")
  public ThreeDSCardholderAccountInfo getAcctInfo() {
    return acctInfo;
  }

  public void setAcctInfo(ThreeDSCardholderAccountInfo acctInfo) {
    this.acctInfo = acctInfo;
  }

  public AReq acctNumber(String acctNumber) {
    this.acctNumber = acctNumber;
    return this;
  }

   /**
   * Get acctNumber
   * @return acctNumber
  **/
  @ApiModelProperty(value = "")
  public String getAcctNumber() {
    return acctNumber;
  }

  public void setAcctNumber(String acctNumber) {
    this.acctNumber = acctNumber;
  }

  public AReq acctType(String acctType) {
    this.acctType = acctType;
    return this;
  }

   /**
   * Get acctType
   * @return acctType
  **/
  @ApiModelProperty(value = "")
  public String getAcctType() {
    return acctType;
  }

  public void setAcctType(String acctType) {
    this.acctType = acctType;
  }

  public AReq acquirerBIN(String acquirerBIN) {
    this.acquirerBIN = acquirerBIN;
    return this;
  }

   /**
   * Get acquirerBIN
   * @return acquirerBIN
  **/
  @ApiModelProperty(value = "")
  public String getAcquirerBIN() {
    return acquirerBIN;
  }

  public void setAcquirerBIN(String acquirerBIN) {
    this.acquirerBIN = acquirerBIN;
  }

  public AReq acquirerMerchantID(String acquirerMerchantID) {
    this.acquirerMerchantID = acquirerMerchantID;
    return this;
  }

   /**
   * Get acquirerMerchantID
   * @return acquirerMerchantID
  **/
  @ApiModelProperty(value = "")
  public String getAcquirerMerchantID() {
    return acquirerMerchantID;
  }

  public void setAcquirerMerchantID(String acquirerMerchantID) {
    this.acquirerMerchantID = acquirerMerchantID;
  }

  public AReq addrMatch(String addrMatch) {
    this.addrMatch = addrMatch;
    return this;
  }

   /**
   * Get addrMatch
   * @return addrMatch
  **/
  @ApiModelProperty(value = "")
  public String getAddrMatch() {
    return addrMatch;
  }

  public void setAddrMatch(String addrMatch) {
    this.addrMatch = addrMatch;
  }

  public AReq billAddrCity(String billAddrCity) {
    this.billAddrCity = billAddrCity;
    return this;
  }

   /**
   * Get billAddrCity
   * @return billAddrCity
  **/
  @ApiModelProperty(value = "")
  public String getBillAddrCity() {
    return billAddrCity;
  }

  public void setBillAddrCity(String billAddrCity) {
    this.billAddrCity = billAddrCity;
  }

  public AReq billAddrCountry(String billAddrCountry) {
    this.billAddrCountry = billAddrCountry;
    return this;
  }

   /**
   * Get billAddrCountry
   * @return billAddrCountry
  **/
  @ApiModelProperty(value = "")
  public String getBillAddrCountry() {
    return billAddrCountry;
  }

  public void setBillAddrCountry(String billAddrCountry) {
    this.billAddrCountry = billAddrCountry;
  }

  public AReq billAddrLine1(String billAddrLine1) {
    this.billAddrLine1 = billAddrLine1;
    return this;
  }

   /**
   * Get billAddrLine1
   * @return billAddrLine1
  **/
  @ApiModelProperty(value = "")
  public String getBillAddrLine1() {
    return billAddrLine1;
  }

  public void setBillAddrLine1(String billAddrLine1) {
    this.billAddrLine1 = billAddrLine1;
  }

  public AReq billAddrLine2(String billAddrLine2) {
    this.billAddrLine2 = billAddrLine2;
    return this;
  }

   /**
   * Get billAddrLine2
   * @return billAddrLine2
  **/
  @ApiModelProperty(value = "")
  public String getBillAddrLine2() {
    return billAddrLine2;
  }

  public void setBillAddrLine2(String billAddrLine2) {
    this.billAddrLine2 = billAddrLine2;
  }

  public AReq billAddrLine3(String billAddrLine3) {
    this.billAddrLine3 = billAddrLine3;
    return this;
  }

   /**
   * Get billAddrLine3
   * @return billAddrLine3
  **/
  @ApiModelProperty(value = "")
  public String getBillAddrLine3() {
    return billAddrLine3;
  }

  public void setBillAddrLine3(String billAddrLine3) {
    this.billAddrLine3 = billAddrLine3;
  }

  public AReq billAddrPostCode(String billAddrPostCode) {
    this.billAddrPostCode = billAddrPostCode;
    return this;
  }

   /**
   * Get billAddrPostCode
   * @return billAddrPostCode
  **/
  @ApiModelProperty(value = "")
  public String getBillAddrPostCode() {
    return billAddrPostCode;
  }

  public void setBillAddrPostCode(String billAddrPostCode) {
    this.billAddrPostCode = billAddrPostCode;
  }

  public AReq billAddrState(String billAddrState) {
    this.billAddrState = billAddrState;
    return this;
  }

   /**
   * Get billAddrState
   * @return billAddrState
  **/
  @ApiModelProperty(value = "")
  public String getBillAddrState() {
    return billAddrState;
  }

  public void setBillAddrState(String billAddrState) {
    this.billAddrState = billAddrState;
  }

  public AReq broadInfo(Object broadInfo) {
    this.broadInfo = broadInfo;
    return this;
  }

   /**
   * Get broadInfo
   * @return broadInfo
  **/
  @ApiModelProperty(value = "")
  public Object getBroadInfo() {
    return broadInfo;
  }

  public void setBroadInfo(Object broadInfo) {
    this.broadInfo = broadInfo;
  }

  public AReq browserAcceptHeader(String browserAcceptHeader) {
    this.browserAcceptHeader = browserAcceptHeader;
    return this;
  }

   /**
   * Get browserAcceptHeader
   * @return browserAcceptHeader
  **/
  @ApiModelProperty(value = "")
  public String getBrowserAcceptHeader() {
    return browserAcceptHeader;
  }

  public void setBrowserAcceptHeader(String browserAcceptHeader) {
    this.browserAcceptHeader = browserAcceptHeader;
  }

  public AReq browserColorDepth(String browserColorDepth) {
    this.browserColorDepth = browserColorDepth;
    return this;
  }

   /**
   * Get browserColorDepth
   * @return browserColorDepth
  **/
  @ApiModelProperty(value = "")
  public String getBrowserColorDepth() {
    return browserColorDepth;
  }

  public void setBrowserColorDepth(String browserColorDepth) {
    this.browserColorDepth = browserColorDepth;
  }

  public AReq browserIP(String browserIP) {
    this.browserIP = browserIP;
    return this;
  }

   /**
   * Get browserIP
   * @return browserIP
  **/
  @ApiModelProperty(value = "")
  public String getBrowserIP() {
    return browserIP;
  }

  public void setBrowserIP(String browserIP) {
    this.browserIP = browserIP;
  }

  public AReq browserJavaEnabled(Boolean browserJavaEnabled) {
    this.browserJavaEnabled = browserJavaEnabled;
    return this;
  }

   /**
   * Get browserJavaEnabled
   * @return browserJavaEnabled
  **/
  @ApiModelProperty(value = "")
  public Boolean isBrowserJavaEnabled() {
    return browserJavaEnabled;
  }

  public void setBrowserJavaEnabled(Boolean browserJavaEnabled) {
    this.browserJavaEnabled = browserJavaEnabled;
  }

  public AReq browserJavascriptEnabled(Boolean browserJavascriptEnabled) {
    this.browserJavascriptEnabled = browserJavascriptEnabled;
    return this;
  }

   /**
   * Get browserJavascriptEnabled
   * @return browserJavascriptEnabled
  **/
  @ApiModelProperty(value = "")
  public Boolean isBrowserJavascriptEnabled() {
    return browserJavascriptEnabled;
  }

  public void setBrowserJavascriptEnabled(Boolean browserJavascriptEnabled) {
    this.browserJavascriptEnabled = browserJavascriptEnabled;
  }

  public AReq browserLanguage(String browserLanguage) {
    this.browserLanguage = browserLanguage;
    return this;
  }

   /**
   * Get browserLanguage
   * @return browserLanguage
  **/
  @ApiModelProperty(value = "")
  public String getBrowserLanguage() {
    return browserLanguage;
  }

  public void setBrowserLanguage(String browserLanguage) {
    this.browserLanguage = browserLanguage;
  }

  public AReq browserScreenHeight(String browserScreenHeight) {
    this.browserScreenHeight = browserScreenHeight;
    return this;
  }

   /**
   * Get browserScreenHeight
   * @return browserScreenHeight
  **/
  @ApiModelProperty(value = "")
  public String getBrowserScreenHeight() {
    return browserScreenHeight;
  }

  public void setBrowserScreenHeight(String browserScreenHeight) {
    this.browserScreenHeight = browserScreenHeight;
  }

  public AReq browserScreenWidth(String browserScreenWidth) {
    this.browserScreenWidth = browserScreenWidth;
    return this;
  }

   /**
   * Get browserScreenWidth
   * @return browserScreenWidth
  **/
  @ApiModelProperty(value = "")
  public String getBrowserScreenWidth() {
    return browserScreenWidth;
  }

  public void setBrowserScreenWidth(String browserScreenWidth) {
    this.browserScreenWidth = browserScreenWidth;
  }

  public AReq browserTZ(String browserTZ) {
    this.browserTZ = browserTZ;
    return this;
  }

   /**
   * Get browserTZ
   * @return browserTZ
  **/
  @ApiModelProperty(value = "")
  public String getBrowserTZ() {
    return browserTZ;
  }

  public void setBrowserTZ(String browserTZ) {
    this.browserTZ = browserTZ;
  }

  public AReq browserUserAgent(String browserUserAgent) {
    this.browserUserAgent = browserUserAgent;
    return this;
  }

   /**
   * Get browserUserAgent
   * @return browserUserAgent
  **/
  @ApiModelProperty(value = "")
  public String getBrowserUserAgent() {
    return browserUserAgent;
  }

  public void setBrowserUserAgent(String browserUserAgent) {
    this.browserUserAgent = browserUserAgent;
  }

  public AReq cardExpiryDate(String cardExpiryDate) {
    this.cardExpiryDate = cardExpiryDate;
    return this;
  }

   /**
   * Get cardExpiryDate
   * @return cardExpiryDate
  **/
  @ApiModelProperty(value = "")
  public String getCardExpiryDate() {
    return cardExpiryDate;
  }

  public void setCardExpiryDate(String cardExpiryDate) {
    this.cardExpiryDate = cardExpiryDate;
  }

  public AReq cardholderName(String cardholderName) {
    this.cardholderName = cardholderName;
    return this;
  }

   /**
   * Get cardholderName
   * @return cardholderName
  **/
  @ApiModelProperty(value = "")
  public String getCardholderName() {
    return cardholderName;
  }

  public void setCardholderName(String cardholderName) {
    this.cardholderName = cardholderName;
  }

  public AReq deviceChannel(String deviceChannel) {
    this.deviceChannel = deviceChannel;
    return this;
  }

   /**
   * Get deviceChannel
   * @return deviceChannel
  **/
  @ApiModelProperty(value = "")
  public String getDeviceChannel() {
    return deviceChannel;
  }

  public void setDeviceChannel(String deviceChannel) {
    this.deviceChannel = deviceChannel;
  }

  public AReq deviceInfo(Object deviceInfo) {
    this.deviceInfo = deviceInfo;
    return this;
  }

   /**
   * Get deviceInfo
   * @return deviceInfo
  **/
  @ApiModelProperty(value = "")
  public Object getDeviceInfo() {
    return deviceInfo;
  }

  public void setDeviceInfo(Object deviceInfo) {
    this.deviceInfo = deviceInfo;
  }

  public AReq deviceRenderOptions(ThreeDSSdkRenderingOptions deviceRenderOptions) {
    this.deviceRenderOptions = deviceRenderOptions;
    return this;
  }

   /**
   * Get deviceRenderOptions
   * @return deviceRenderOptions
  **/
  @ApiModelProperty(value = "")
  public ThreeDSSdkRenderingOptions getDeviceRenderOptions() {
    return deviceRenderOptions;
  }

  public void setDeviceRenderOptions(ThreeDSSdkRenderingOptions deviceRenderOptions) {
    this.deviceRenderOptions = deviceRenderOptions;
  }

  public AReq dsReferenceNumber(String dsReferenceNumber) {
    this.dsReferenceNumber = dsReferenceNumber;
    return this;
  }

   /**
   * Get dsReferenceNumber
   * @return dsReferenceNumber
  **/
  @ApiModelProperty(value = "")
  public String getDsReferenceNumber() {
    return dsReferenceNumber;
  }

  public void setDsReferenceNumber(String dsReferenceNumber) {
    this.dsReferenceNumber = dsReferenceNumber;
  }

  public AReq dsTransID(String dsTransID) {
    this.dsTransID = dsTransID;
    return this;
  }

   /**
   * Get dsTransID
   * @return dsTransID
  **/
  @ApiModelProperty(value = "")
  public String getDsTransID() {
    return dsTransID;
  }

  public void setDsTransID(String dsTransID) {
    this.dsTransID = dsTransID;
  }

  public AReq dsURL(String dsURL) {
    this.dsURL = dsURL;
    return this;
  }

   /**
   * Get dsURL
   * @return dsURL
  **/
  @ApiModelProperty(value = "")
  public String getDsURL() {
    return dsURL;
  }

  public void setDsURL(String dsURL) {
    this.dsURL = dsURL;
  }

  public AReq email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @ApiModelProperty(value = "")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public AReq homePhone(Phone homePhone) {
    this.homePhone = homePhone;
    return this;
  }

   /**
   * Get homePhone
   * @return homePhone
  **/
  @ApiModelProperty(value = "")
  public Phone getHomePhone() {
    return homePhone;
  }

  public void setHomePhone(Phone homePhone) {
    this.homePhone = homePhone;
  }

  public AReq mcc(String mcc) {
    this.mcc = mcc;
    return this;
  }

   /**
   * Get mcc
   * @return mcc
  **/
  @ApiModelProperty(value = "")
  public String getMcc() {
    return mcc;
  }

  public void setMcc(String mcc) {
    this.mcc = mcc;
  }

  public AReq merchantCountryCode(String merchantCountryCode) {
    this.merchantCountryCode = merchantCountryCode;
    return this;
  }

   /**
   * Get merchantCountryCode
   * @return merchantCountryCode
  **/
  @ApiModelProperty(value = "")
  public String getMerchantCountryCode() {
    return merchantCountryCode;
  }

  public void setMerchantCountryCode(String merchantCountryCode) {
    this.merchantCountryCode = merchantCountryCode;
  }

  public AReq merchantName(String merchantName) {
    this.merchantName = merchantName;
    return this;
  }

   /**
   * Get merchantName
   * @return merchantName
  **/
  @ApiModelProperty(value = "")
  public String getMerchantName() {
    return merchantName;
  }

  public void setMerchantName(String merchantName) {
    this.merchantName = merchantName;
  }

  public AReq merchantRiskIndicator(ThreeDSMerchantRiskIndicator merchantRiskIndicator) {
    this.merchantRiskIndicator = merchantRiskIndicator;
    return this;
  }

   /**
   * Get merchantRiskIndicator
   * @return merchantRiskIndicator
  **/
  @ApiModelProperty(value = "")
  public ThreeDSMerchantRiskIndicator getMerchantRiskIndicator() {
    return merchantRiskIndicator;
  }

  public void setMerchantRiskIndicator(ThreeDSMerchantRiskIndicator merchantRiskIndicator) {
    this.merchantRiskIndicator = merchantRiskIndicator;
  }

  public AReq messageCategory(String messageCategory) {
    this.messageCategory = messageCategory;
    return this;
  }

   /**
   * Get messageCategory
   * @return messageCategory
  **/
  @ApiModelProperty(value = "")
  public String getMessageCategory() {
    return messageCategory;
  }

  public void setMessageCategory(String messageCategory) {
    this.messageCategory = messageCategory;
  }

  public AReq messageExtension(List<Extension> messageExtension) {
    this.messageExtension = messageExtension;
    return this;
  }

  public AReq addMessageExtensionItem(Extension messageExtensionItem) {
    if (this.messageExtension == null) {
      this.messageExtension = new ArrayList<Extension>();
    }
    this.messageExtension.add(messageExtensionItem);
    return this;
  }

   /**
   * Get messageExtension
   * @return messageExtension
  **/
  @ApiModelProperty(value = "")
  public List<Extension> getMessageExtension() {
    return messageExtension;
  }

  public void setMessageExtension(List<Extension> messageExtension) {
    this.messageExtension = messageExtension;
  }

  public AReq mobilePhone(Phone mobilePhone) {
    this.mobilePhone = mobilePhone;
    return this;
  }

   /**
   * Get mobilePhone
   * @return mobilePhone
  **/
  @ApiModelProperty(value = "")
  public Phone getMobilePhone() {
    return mobilePhone;
  }

  public void setMobilePhone(Phone mobilePhone) {
    this.mobilePhone = mobilePhone;
  }

  public AReq notificationURL(String notificationURL) {
    this.notificationURL = notificationURL;
    return this;
  }

   /**
   * Get notificationURL
   * @return notificationURL
  **/
  @ApiModelProperty(value = "")
  public String getNotificationURL() {
    return notificationURL;
  }

  public void setNotificationURL(String notificationURL) {
    this.notificationURL = notificationURL;
  }

  public AReq payTokenInd(Boolean payTokenInd) {
    this.payTokenInd = payTokenInd;
    return this;
  }

   /**
   * Get payTokenInd
   * @return payTokenInd
  **/
  @ApiModelProperty(value = "")
  public Boolean isPayTokenInd() {
    return payTokenInd;
  }

  public void setPayTokenInd(Boolean payTokenInd) {
    this.payTokenInd = payTokenInd;
  }

  public AReq payTokenSource(String payTokenSource) {
    this.payTokenSource = payTokenSource;
    return this;
  }

   /**
   * Get payTokenSource
   * @return payTokenSource
  **/
  @ApiModelProperty(value = "")
  public String getPayTokenSource() {
    return payTokenSource;
  }

  public void setPayTokenSource(String payTokenSource) {
    this.payTokenSource = payTokenSource;
  }

  public AReq purchaseAmount(String purchaseAmount) {
    this.purchaseAmount = purchaseAmount;
    return this;
  }

   /**
   * Get purchaseAmount
   * @return purchaseAmount
  **/
  @ApiModelProperty(value = "")
  public String getPurchaseAmount() {
    return purchaseAmount;
  }

  public void setPurchaseAmount(String purchaseAmount) {
    this.purchaseAmount = purchaseAmount;
  }

  public AReq purchaseCurrency(String purchaseCurrency) {
    this.purchaseCurrency = purchaseCurrency;
    return this;
  }

   /**
   * Get purchaseCurrency
   * @return purchaseCurrency
  **/
  @ApiModelProperty(value = "")
  public String getPurchaseCurrency() {
    return purchaseCurrency;
  }

  public void setPurchaseCurrency(String purchaseCurrency) {
    this.purchaseCurrency = purchaseCurrency;
  }

  public AReq purchaseDate(String purchaseDate) {
    this.purchaseDate = purchaseDate;
    return this;
  }

   /**
   * Get purchaseDate
   * @return purchaseDate
  **/
  @ApiModelProperty(value = "")
  public String getPurchaseDate() {
    return purchaseDate;
  }

  public void setPurchaseDate(String purchaseDate) {
    this.purchaseDate = purchaseDate;
  }

  public AReq purchaseExponent(String purchaseExponent) {
    this.purchaseExponent = purchaseExponent;
    return this;
  }

   /**
   * Get purchaseExponent
   * @return purchaseExponent
  **/
  @ApiModelProperty(value = "")
  public String getPurchaseExponent() {
    return purchaseExponent;
  }

  public void setPurchaseExponent(String purchaseExponent) {
    this.purchaseExponent = purchaseExponent;
  }

  public AReq purchaseInstalData(String purchaseInstalData) {
    this.purchaseInstalData = purchaseInstalData;
    return this;
  }

   /**
   * Get purchaseInstalData
   * @return purchaseInstalData
  **/
  @ApiModelProperty(value = "")
  public String getPurchaseInstalData() {
    return purchaseInstalData;
  }

  public void setPurchaseInstalData(String purchaseInstalData) {
    this.purchaseInstalData = purchaseInstalData;
  }

  public AReq recurringExpiry(String recurringExpiry) {
    this.recurringExpiry = recurringExpiry;
    return this;
  }

   /**
   * Get recurringExpiry
   * @return recurringExpiry
  **/
  @ApiModelProperty(value = "")
  public String getRecurringExpiry() {
    return recurringExpiry;
  }

  public void setRecurringExpiry(String recurringExpiry) {
    this.recurringExpiry = recurringExpiry;
  }

  public AReq recurringFrequency(String recurringFrequency) {
    this.recurringFrequency = recurringFrequency;
    return this;
  }

   /**
   * Get recurringFrequency
   * @return recurringFrequency
  **/
  @ApiModelProperty(value = "")
  public String getRecurringFrequency() {
    return recurringFrequency;
  }

  public void setRecurringFrequency(String recurringFrequency) {
    this.recurringFrequency = recurringFrequency;
  }

  public AReq sdkAppID(String sdkAppID) {
    this.sdkAppID = sdkAppID;
    return this;
  }

   /**
   * Get sdkAppID
   * @return sdkAppID
  **/
  @ApiModelProperty(value = "")
  public String getSdkAppID() {
    return sdkAppID;
  }

  public void setSdkAppID(String sdkAppID) {
    this.sdkAppID = sdkAppID;
  }

  public AReq sdkEncData(String sdkEncData) {
    this.sdkEncData = sdkEncData;
    return this;
  }

   /**
   * Get sdkEncData
   * @return sdkEncData
  **/
  @ApiModelProperty(value = "")
  public String getSdkEncData() {
    return sdkEncData;
  }

  public void setSdkEncData(String sdkEncData) {
    this.sdkEncData = sdkEncData;
  }

  public AReq sdkEphemPubKey(SdkEphemPubKey sdkEphemPubKey) {
    this.sdkEphemPubKey = sdkEphemPubKey;
    return this;
  }

   /**
   * Get sdkEphemPubKey
   * @return sdkEphemPubKey
  **/
  @ApiModelProperty(value = "")
  public SdkEphemPubKey getSdkEphemPubKey() {
    return sdkEphemPubKey;
  }

  public void setSdkEphemPubKey(SdkEphemPubKey sdkEphemPubKey) {
    this.sdkEphemPubKey = sdkEphemPubKey;
  }

  public AReq sdkMaxTimeout(String sdkMaxTimeout) {
    this.sdkMaxTimeout = sdkMaxTimeout;
    return this;
  }

   /**
   * Get sdkMaxTimeout
   * @return sdkMaxTimeout
  **/
  @ApiModelProperty(value = "")
  public String getSdkMaxTimeout() {
    return sdkMaxTimeout;
  }

  public void setSdkMaxTimeout(String sdkMaxTimeout) {
    this.sdkMaxTimeout = sdkMaxTimeout;
  }

  public AReq sdkReferenceNumber(String sdkReferenceNumber) {
    this.sdkReferenceNumber = sdkReferenceNumber;
    return this;
  }

   /**
   * Get sdkReferenceNumber
   * @return sdkReferenceNumber
  **/
  @ApiModelProperty(value = "")
  public String getSdkReferenceNumber() {
    return sdkReferenceNumber;
  }

  public void setSdkReferenceNumber(String sdkReferenceNumber) {
    this.sdkReferenceNumber = sdkReferenceNumber;
  }

  public AReq sdkTransID(String sdkTransID) {
    this.sdkTransID = sdkTransID;
    return this;
  }

   /**
   * Get sdkTransID
   * @return sdkTransID
  **/
  @ApiModelProperty(value = "")
  public String getSdkTransID() {
    return sdkTransID;
  }

  public void setSdkTransID(String sdkTransID) {
    this.sdkTransID = sdkTransID;
  }

  public AReq shipAddrCity(String shipAddrCity) {
    this.shipAddrCity = shipAddrCity;
    return this;
  }

   /**
   * Get shipAddrCity
   * @return shipAddrCity
  **/
  @ApiModelProperty(value = "")
  public String getShipAddrCity() {
    return shipAddrCity;
  }

  public void setShipAddrCity(String shipAddrCity) {
    this.shipAddrCity = shipAddrCity;
  }

  public AReq shipAddrCountry(String shipAddrCountry) {
    this.shipAddrCountry = shipAddrCountry;
    return this;
  }

   /**
   * Get shipAddrCountry
   * @return shipAddrCountry
  **/
  @ApiModelProperty(value = "")
  public String getShipAddrCountry() {
    return shipAddrCountry;
  }

  public void setShipAddrCountry(String shipAddrCountry) {
    this.shipAddrCountry = shipAddrCountry;
  }

  public AReq shipAddrLine1(String shipAddrLine1) {
    this.shipAddrLine1 = shipAddrLine1;
    return this;
  }

   /**
   * Get shipAddrLine1
   * @return shipAddrLine1
  **/
  @ApiModelProperty(value = "")
  public String getShipAddrLine1() {
    return shipAddrLine1;
  }

  public void setShipAddrLine1(String shipAddrLine1) {
    this.shipAddrLine1 = shipAddrLine1;
  }

  public AReq shipAddrLine2(String shipAddrLine2) {
    this.shipAddrLine2 = shipAddrLine2;
    return this;
  }

   /**
   * Get shipAddrLine2
   * @return shipAddrLine2
  **/
  @ApiModelProperty(value = "")
  public String getShipAddrLine2() {
    return shipAddrLine2;
  }

  public void setShipAddrLine2(String shipAddrLine2) {
    this.shipAddrLine2 = shipAddrLine2;
  }

  public AReq shipAddrLine3(String shipAddrLine3) {
    this.shipAddrLine3 = shipAddrLine3;
    return this;
  }

   /**
   * Get shipAddrLine3
   * @return shipAddrLine3
  **/
  @ApiModelProperty(value = "")
  public String getShipAddrLine3() {
    return shipAddrLine3;
  }

  public void setShipAddrLine3(String shipAddrLine3) {
    this.shipAddrLine3 = shipAddrLine3;
  }

  public AReq shipAddrPostCode(String shipAddrPostCode) {
    this.shipAddrPostCode = shipAddrPostCode;
    return this;
  }

   /**
   * Get shipAddrPostCode
   * @return shipAddrPostCode
  **/
  @ApiModelProperty(value = "")
  public String getShipAddrPostCode() {
    return shipAddrPostCode;
  }

  public void setShipAddrPostCode(String shipAddrPostCode) {
    this.shipAddrPostCode = shipAddrPostCode;
  }

  public AReq shipAddrState(String shipAddrState) {
    this.shipAddrState = shipAddrState;
    return this;
  }

   /**
   * Get shipAddrState
   * @return shipAddrState
  **/
  @ApiModelProperty(value = "")
  public String getShipAddrState() {
    return shipAddrState;
  }

  public void setShipAddrState(String shipAddrState) {
    this.shipAddrState = shipAddrState;
  }

  public AReq threeDSCompInd(String threeDSCompInd) {
    this.threeDSCompInd = threeDSCompInd;
    return this;
  }

   /**
   * Get threeDSCompInd
   * @return threeDSCompInd
  **/
  @ApiModelProperty(value = "")
  public String getThreeDSCompInd() {
    return threeDSCompInd;
  }

  public void setThreeDSCompInd(String threeDSCompInd) {
    this.threeDSCompInd = threeDSCompInd;
  }

  public AReq threeDSReqAuthMethodInd(String threeDSReqAuthMethodInd) {
    this.threeDSReqAuthMethodInd = threeDSReqAuthMethodInd;
    return this;
  }

   /**
   * Get threeDSReqAuthMethodInd
   * @return threeDSReqAuthMethodInd
  **/
  @ApiModelProperty(value = "")
  public String getThreeDSReqAuthMethodInd() {
    return threeDSReqAuthMethodInd;
  }

  public void setThreeDSReqAuthMethodInd(String threeDSReqAuthMethodInd) {
    this.threeDSReqAuthMethodInd = threeDSReqAuthMethodInd;
  }

  public AReq threeDSRequestorAuthenticationInd(String threeDSRequestorAuthenticationInd) {
    this.threeDSRequestorAuthenticationInd = threeDSRequestorAuthenticationInd;
    return this;
  }

   /**
   * Get threeDSRequestorAuthenticationInd
   * @return threeDSRequestorAuthenticationInd
  **/
  @ApiModelProperty(value = "")
  public String getThreeDSRequestorAuthenticationInd() {
    return threeDSRequestorAuthenticationInd;
  }

  public void setThreeDSRequestorAuthenticationInd(String threeDSRequestorAuthenticationInd) {
    this.threeDSRequestorAuthenticationInd = threeDSRequestorAuthenticationInd;
  }

  public AReq threeDSRequestorAuthenticationInfo(ThreeDSRequestorAuthInfo threeDSRequestorAuthenticationInfo) {
    this.threeDSRequestorAuthenticationInfo = threeDSRequestorAuthenticationInfo;
    return this;
  }

   /**
   * Get threeDSRequestorAuthenticationInfo
   * @return threeDSRequestorAuthenticationInfo
  **/
  @ApiModelProperty(value = "")
  public ThreeDSRequestorAuthInfo getThreeDSRequestorAuthenticationInfo() {
    return threeDSRequestorAuthenticationInfo;
  }

  public void setThreeDSRequestorAuthenticationInfo(ThreeDSRequestorAuthInfo threeDSRequestorAuthenticationInfo) {
    this.threeDSRequestorAuthenticationInfo = threeDSRequestorAuthenticationInfo;
  }

  public AReq threeDSRequestorChallengeInd(String threeDSRequestorChallengeInd) {
    this.threeDSRequestorChallengeInd = threeDSRequestorChallengeInd;
    return this;
  }

   /**
   * Get threeDSRequestorChallengeInd
   * @return threeDSRequestorChallengeInd
  **/
  @ApiModelProperty(value = "")
  public String getThreeDSRequestorChallengeInd() {
    return threeDSRequestorChallengeInd;
  }

  public void setThreeDSRequestorChallengeInd(String threeDSRequestorChallengeInd) {
    this.threeDSRequestorChallengeInd = threeDSRequestorChallengeInd;
  }

  public AReq threeDSRequestorDecMaxTime(String threeDSRequestorDecMaxTime) {
    this.threeDSRequestorDecMaxTime = threeDSRequestorDecMaxTime;
    return this;
  }

   /**
   * Get threeDSRequestorDecMaxTime
   * @return threeDSRequestorDecMaxTime
  **/
  @ApiModelProperty(value = "")
  public String getThreeDSRequestorDecMaxTime() {
    return threeDSRequestorDecMaxTime;
  }

  public void setThreeDSRequestorDecMaxTime(String threeDSRequestorDecMaxTime) {
    this.threeDSRequestorDecMaxTime = threeDSRequestorDecMaxTime;
  }

  public AReq threeDSRequestorDecReqInd(String threeDSRequestorDecReqInd) {
    this.threeDSRequestorDecReqInd = threeDSRequestorDecReqInd;
    return this;
  }

   /**
   * Get threeDSRequestorDecReqInd
   * @return threeDSRequestorDecReqInd
  **/
  @ApiModelProperty(value = "")
  public String getThreeDSRequestorDecReqInd() {
    return threeDSRequestorDecReqInd;
  }

  public void setThreeDSRequestorDecReqInd(String threeDSRequestorDecReqInd) {
    this.threeDSRequestorDecReqInd = threeDSRequestorDecReqInd;
  }

  public AReq threeDSRequestorID(String threeDSRequestorID) {
    this.threeDSRequestorID = threeDSRequestorID;
    return this;
  }

   /**
   * Get threeDSRequestorID
   * @return threeDSRequestorID
  **/
  @ApiModelProperty(value = "")
  public String getThreeDSRequestorID() {
    return threeDSRequestorID;
  }

  public void setThreeDSRequestorID(String threeDSRequestorID) {
    this.threeDSRequestorID = threeDSRequestorID;
  }

  public AReq threeDSRequestorName(String threeDSRequestorName) {
    this.threeDSRequestorName = threeDSRequestorName;
    return this;
  }

   /**
   * Get threeDSRequestorName
   * @return threeDSRequestorName
  **/
  @ApiModelProperty(value = "")
  public String getThreeDSRequestorName() {
    return threeDSRequestorName;
  }

  public void setThreeDSRequestorName(String threeDSRequestorName) {
    this.threeDSRequestorName = threeDSRequestorName;
  }

  public AReq threeDSRequestorPriorAuthenticationInfo(ThreeDSRequestorPriorAuthInfo threeDSRequestorPriorAuthenticationInfo) {
    this.threeDSRequestorPriorAuthenticationInfo = threeDSRequestorPriorAuthenticationInfo;
    return this;
  }

   /**
   * Get threeDSRequestorPriorAuthenticationInfo
   * @return threeDSRequestorPriorAuthenticationInfo
  **/
  @ApiModelProperty(value = "")
  public ThreeDSRequestorPriorAuthInfo getThreeDSRequestorPriorAuthenticationInfo() {
    return threeDSRequestorPriorAuthenticationInfo;
  }

  public void setThreeDSRequestorPriorAuthenticationInfo(ThreeDSRequestorPriorAuthInfo threeDSRequestorPriorAuthenticationInfo) {
    this.threeDSRequestorPriorAuthenticationInfo = threeDSRequestorPriorAuthenticationInfo;
  }

  public AReq threeDSRequestorURL(String threeDSRequestorURL) {
    this.threeDSRequestorURL = threeDSRequestorURL;
    return this;
  }

   /**
   * Get threeDSRequestorURL
   * @return threeDSRequestorURL
  **/
  @ApiModelProperty(value = "")
  public String getThreeDSRequestorURL() {
    return threeDSRequestorURL;
  }

  public void setThreeDSRequestorURL(String threeDSRequestorURL) {
    this.threeDSRequestorURL = threeDSRequestorURL;
  }

  public AReq threeDSServerOperatorID(String threeDSServerOperatorID) {
    this.threeDSServerOperatorID = threeDSServerOperatorID;
    return this;
  }

   /**
   * Get threeDSServerOperatorID
   * @return threeDSServerOperatorID
  **/
  @ApiModelProperty(value = "")
  public String getThreeDSServerOperatorID() {
    return threeDSServerOperatorID;
  }

  public void setThreeDSServerOperatorID(String threeDSServerOperatorID) {
    this.threeDSServerOperatorID = threeDSServerOperatorID;
  }

  public AReq threeDSServerRefNumber(String threeDSServerRefNumber) {
    this.threeDSServerRefNumber = threeDSServerRefNumber;
    return this;
  }

   /**
   * Get threeDSServerRefNumber
   * @return threeDSServerRefNumber
  **/
  @ApiModelProperty(value = "")
  public String getThreeDSServerRefNumber() {
    return threeDSServerRefNumber;
  }

  public void setThreeDSServerRefNumber(String threeDSServerRefNumber) {
    this.threeDSServerRefNumber = threeDSServerRefNumber;
  }

  public AReq threeDSServerTransID(String threeDSServerTransID) {
    this.threeDSServerTransID = threeDSServerTransID;
    return this;
  }

   /**
   * Get threeDSServerTransID
   * @return threeDSServerTransID
  **/
  @ApiModelProperty(value = "")
  public String getThreeDSServerTransID() {
    return threeDSServerTransID;
  }

  public void setThreeDSServerTransID(String threeDSServerTransID) {
    this.threeDSServerTransID = threeDSServerTransID;
  }

  public AReq threeDSServerURL(String threeDSServerURL) {
    this.threeDSServerURL = threeDSServerURL;
    return this;
  }

   /**
   * Get threeDSServerURL
   * @return threeDSServerURL
  **/
  @ApiModelProperty(value = "")
  public String getThreeDSServerURL() {
    return threeDSServerURL;
  }

  public void setThreeDSServerURL(String threeDSServerURL) {
    this.threeDSServerURL = threeDSServerURL;
  }

  public AReq threeRIInd(String threeRIInd) {
    this.threeRIInd = threeRIInd;
    return this;
  }

   /**
   * Get threeRIInd
   * @return threeRIInd
  **/
  @ApiModelProperty(value = "")
  public String getThreeRIInd() {
    return threeRIInd;
  }

  public void setThreeRIInd(String threeRIInd) {
    this.threeRIInd = threeRIInd;
  }

  public AReq transType(String transType) {
    this.transType = transType;
    return this;
  }

   /**
   * Get transType
   * @return transType
  **/
  @ApiModelProperty(value = "")
  public String getTransType() {
    return transType;
  }

  public void setTransType(String transType) {
    this.transType = transType;
  }

  public AReq whiteListStatus(String whiteListStatus) {
    this.whiteListStatus = whiteListStatus;
    return this;
  }

   /**
   * Get whiteListStatus
   * @return whiteListStatus
  **/
  @ApiModelProperty(value = "")
  public String getWhiteListStatus() {
    return whiteListStatus;
  }

  public void setWhiteListStatus(String whiteListStatus) {
    this.whiteListStatus = whiteListStatus;
  }

  public AReq whiteListStatusSource(String whiteListStatusSource) {
    this.whiteListStatusSource = whiteListStatusSource;
    return this;
  }

   /**
   * Get whiteListStatusSource
   * @return whiteListStatusSource
  **/
  @ApiModelProperty(value = "")
  public String getWhiteListStatusSource() {
    return whiteListStatusSource;
  }

  public void setWhiteListStatusSource(String whiteListStatusSource) {
    this.whiteListStatusSource = whiteListStatusSource;
  }

  public AReq workPhone(Phone workPhone) {
    this.workPhone = workPhone;
    return this;
  }

   /**
   * Get workPhone
   * @return workPhone
  **/
  @ApiModelProperty(value = "")
  public Phone getWorkPhone() {
    return workPhone;
  }

  public void setWorkPhone(Phone workPhone) {
    this.workPhone = workPhone;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AReq areq = (AReq) o;
    return Objects.equals(this.acctID, areq.acctID) &&
        Objects.equals(this.acctInfo, areq.acctInfo) &&
        Objects.equals(this.acctNumber, areq.acctNumber) &&
        Objects.equals(this.acctType, areq.acctType) &&
        Objects.equals(this.acquirerBIN, areq.acquirerBIN) &&
        Objects.equals(this.acquirerMerchantID, areq.acquirerMerchantID) &&
        Objects.equals(this.addrMatch, areq.addrMatch) &&
        Objects.equals(this.billAddrCity, areq.billAddrCity) &&
        Objects.equals(this.billAddrCountry, areq.billAddrCountry) &&
        Objects.equals(this.billAddrLine1, areq.billAddrLine1) &&
        Objects.equals(this.billAddrLine2, areq.billAddrLine2) &&
        Objects.equals(this.billAddrLine3, areq.billAddrLine3) &&
        Objects.equals(this.billAddrPostCode, areq.billAddrPostCode) &&
        Objects.equals(this.billAddrState, areq.billAddrState) &&
        Objects.equals(this.broadInfo, areq.broadInfo) &&
        Objects.equals(this.browserAcceptHeader, areq.browserAcceptHeader) &&
        Objects.equals(this.browserColorDepth, areq.browserColorDepth) &&
        Objects.equals(this.browserIP, areq.browserIP) &&
        Objects.equals(this.browserJavaEnabled, areq.browserJavaEnabled) &&
        Objects.equals(this.browserJavascriptEnabled, areq.browserJavascriptEnabled) &&
        Objects.equals(this.browserLanguage, areq.browserLanguage) &&
        Objects.equals(this.browserScreenHeight, areq.browserScreenHeight) &&
        Objects.equals(this.browserScreenWidth, areq.browserScreenWidth) &&
        Objects.equals(this.browserTZ, areq.browserTZ) &&
        Objects.equals(this.browserUserAgent, areq.browserUserAgent) &&
        Objects.equals(this.cardExpiryDate, areq.cardExpiryDate) &&
        Objects.equals(this.cardholderName, areq.cardholderName) &&
        Objects.equals(this.deviceChannel, areq.deviceChannel) &&
        Objects.equals(this.deviceInfo, areq.deviceInfo) &&
        Objects.equals(this.deviceRenderOptions, areq.deviceRenderOptions) &&
        Objects.equals(this.dsReferenceNumber, areq.dsReferenceNumber) &&
        Objects.equals(this.dsTransID, areq.dsTransID) &&
        Objects.equals(this.dsURL, areq.dsURL) &&
        Objects.equals(this.email, areq.email) &&
        Objects.equals(this.homePhone, areq.homePhone) &&
        Objects.equals(this.mcc, areq.mcc) &&
        Objects.equals(this.merchantCountryCode, areq.merchantCountryCode) &&
        Objects.equals(this.merchantName, areq.merchantName) &&
        Objects.equals(this.merchantRiskIndicator, areq.merchantRiskIndicator) &&
        Objects.equals(this.messageCategory, areq.messageCategory) &&
        Objects.equals(this.messageExtension, areq.messageExtension) &&
        Objects.equals(this.mobilePhone, areq.mobilePhone) &&
        Objects.equals(this.notificationURL, areq.notificationURL) &&
        Objects.equals(this.payTokenInd, areq.payTokenInd) &&
        Objects.equals(this.payTokenSource, areq.payTokenSource) &&
        Objects.equals(this.purchaseAmount, areq.purchaseAmount) &&
        Objects.equals(this.purchaseCurrency, areq.purchaseCurrency) &&
        Objects.equals(this.purchaseDate, areq.purchaseDate) &&
        Objects.equals(this.purchaseExponent, areq.purchaseExponent) &&
        Objects.equals(this.purchaseInstalData, areq.purchaseInstalData) &&
        Objects.equals(this.recurringExpiry, areq.recurringExpiry) &&
        Objects.equals(this.recurringFrequency, areq.recurringFrequency) &&
        Objects.equals(this.sdkAppID, areq.sdkAppID) &&
        Objects.equals(this.sdkEncData, areq.sdkEncData) &&
        Objects.equals(this.sdkEphemPubKey, areq.sdkEphemPubKey) &&
        Objects.equals(this.sdkMaxTimeout, areq.sdkMaxTimeout) &&
        Objects.equals(this.sdkReferenceNumber, areq.sdkReferenceNumber) &&
        Objects.equals(this.sdkTransID, areq.sdkTransID) &&
        Objects.equals(this.shipAddrCity, areq.shipAddrCity) &&
        Objects.equals(this.shipAddrCountry, areq.shipAddrCountry) &&
        Objects.equals(this.shipAddrLine1, areq.shipAddrLine1) &&
        Objects.equals(this.shipAddrLine2, areq.shipAddrLine2) &&
        Objects.equals(this.shipAddrLine3, areq.shipAddrLine3) &&
        Objects.equals(this.shipAddrPostCode, areq.shipAddrPostCode) &&
        Objects.equals(this.shipAddrState, areq.shipAddrState) &&
        Objects.equals(this.threeDSCompInd, areq.threeDSCompInd) &&
        Objects.equals(this.threeDSReqAuthMethodInd, areq.threeDSReqAuthMethodInd) &&
        Objects.equals(this.threeDSRequestorAuthenticationInd, areq.threeDSRequestorAuthenticationInd) &&
        Objects.equals(this.threeDSRequestorAuthenticationInfo, areq.threeDSRequestorAuthenticationInfo) &&
        Objects.equals(this.threeDSRequestorChallengeInd, areq.threeDSRequestorChallengeInd) &&
        Objects.equals(this.threeDSRequestorDecMaxTime, areq.threeDSRequestorDecMaxTime) &&
        Objects.equals(this.threeDSRequestorDecReqInd, areq.threeDSRequestorDecReqInd) &&
        Objects.equals(this.threeDSRequestorID, areq.threeDSRequestorID) &&
        Objects.equals(this.threeDSRequestorName, areq.threeDSRequestorName) &&
        Objects.equals(this.threeDSRequestorPriorAuthenticationInfo, areq.threeDSRequestorPriorAuthenticationInfo) &&
        Objects.equals(this.threeDSRequestorURL, areq.threeDSRequestorURL) &&
        Objects.equals(this.threeDSServerOperatorID, areq.threeDSServerOperatorID) &&
        Objects.equals(this.threeDSServerRefNumber, areq.threeDSServerRefNumber) &&
        Objects.equals(this.threeDSServerTransID, areq.threeDSServerTransID) &&
        Objects.equals(this.threeDSServerURL, areq.threeDSServerURL) &&
        Objects.equals(this.threeRIInd, areq.threeRIInd) &&
        Objects.equals(this.transType, areq.transType) &&
        Objects.equals(this.whiteListStatus, areq.whiteListStatus) &&
        Objects.equals(this.whiteListStatusSource, areq.whiteListStatusSource) &&
        Objects.equals(this.workPhone, areq.workPhone);
  }

  @Override
  public int hashCode() {
    return Objects.hash(acctID, acctInfo, acctNumber, acctType, acquirerBIN, acquirerMerchantID, addrMatch, billAddrCity, billAddrCountry, billAddrLine1, billAddrLine2, billAddrLine3, billAddrPostCode, billAddrState, broadInfo, browserAcceptHeader, browserColorDepth, browserIP, browserJavaEnabled, browserJavascriptEnabled, browserLanguage, browserScreenHeight, browserScreenWidth, browserTZ, browserUserAgent, cardExpiryDate, cardholderName, deviceChannel, deviceInfo, deviceRenderOptions, dsReferenceNumber, dsTransID, dsURL, email, homePhone, mcc, merchantCountryCode, merchantName, merchantRiskIndicator, messageCategory, messageExtension, mobilePhone, notificationURL, payTokenInd, payTokenSource, purchaseAmount, purchaseCurrency, purchaseDate, purchaseExponent, purchaseInstalData, recurringExpiry, recurringFrequency, sdkAppID, sdkEncData, sdkEphemPubKey, sdkMaxTimeout, sdkReferenceNumber, sdkTransID, shipAddrCity, shipAddrCountry, shipAddrLine1, shipAddrLine2, shipAddrLine3, shipAddrPostCode, shipAddrState, threeDSCompInd, threeDSReqAuthMethodInd, threeDSRequestorAuthenticationInd, threeDSRequestorAuthenticationInfo, threeDSRequestorChallengeInd, threeDSRequestorDecMaxTime, threeDSRequestorDecReqInd, threeDSRequestorID, threeDSRequestorName, threeDSRequestorPriorAuthenticationInfo, threeDSRequestorURL, threeDSServerOperatorID, threeDSServerRefNumber, threeDSServerTransID, threeDSServerURL, threeRIInd, transType, whiteListStatus, whiteListStatusSource, workPhone);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AReq {\n");
    
    sb.append("    acctID: ").append(toIndentedString(acctID)).append("\n");
    sb.append("    acctInfo: ").append(toIndentedString(acctInfo)).append("\n");
    sb.append("    acctNumber: ").append(toIndentedString(acctNumber)).append("\n");
    sb.append("    acctType: ").append(toIndentedString(acctType)).append("\n");
    sb.append("    acquirerBIN: ").append(toIndentedString(acquirerBIN)).append("\n");
    sb.append("    acquirerMerchantID: ").append(toIndentedString(acquirerMerchantID)).append("\n");
    sb.append("    addrMatch: ").append(toIndentedString(addrMatch)).append("\n");
    sb.append("    billAddrCity: ").append(toIndentedString(billAddrCity)).append("\n");
    sb.append("    billAddrCountry: ").append(toIndentedString(billAddrCountry)).append("\n");
    sb.append("    billAddrLine1: ").append(toIndentedString(billAddrLine1)).append("\n");
    sb.append("    billAddrLine2: ").append(toIndentedString(billAddrLine2)).append("\n");
    sb.append("    billAddrLine3: ").append(toIndentedString(billAddrLine3)).append("\n");
    sb.append("    billAddrPostCode: ").append(toIndentedString(billAddrPostCode)).append("\n");
    sb.append("    billAddrState: ").append(toIndentedString(billAddrState)).append("\n");
    sb.append("    broadInfo: ").append(toIndentedString(broadInfo)).append("\n");
    sb.append("    browserAcceptHeader: ").append(toIndentedString(browserAcceptHeader)).append("\n");
    sb.append("    browserColorDepth: ").append(toIndentedString(browserColorDepth)).append("\n");
    sb.append("    browserIP: ").append(toIndentedString(browserIP)).append("\n");
    sb.append("    browserJavaEnabled: ").append(toIndentedString(browserJavaEnabled)).append("\n");
    sb.append("    browserJavascriptEnabled: ").append(toIndentedString(browserJavascriptEnabled)).append("\n");
    sb.append("    browserLanguage: ").append(toIndentedString(browserLanguage)).append("\n");
    sb.append("    browserScreenHeight: ").append(toIndentedString(browserScreenHeight)).append("\n");
    sb.append("    browserScreenWidth: ").append(toIndentedString(browserScreenWidth)).append("\n");
    sb.append("    browserTZ: ").append(toIndentedString(browserTZ)).append("\n");
    sb.append("    browserUserAgent: ").append(toIndentedString(browserUserAgent)).append("\n");
    sb.append("    cardExpiryDate: ").append(toIndentedString(cardExpiryDate)).append("\n");
    sb.append("    cardholderName: ").append(toIndentedString(cardholderName)).append("\n");
    sb.append("    deviceChannel: ").append(toIndentedString(deviceChannel)).append("\n");
    sb.append("    deviceInfo: ").append(toIndentedString(deviceInfo)).append("\n");
    sb.append("    deviceRenderOptions: ").append(toIndentedString(deviceRenderOptions)).append("\n");
    sb.append("    dsReferenceNumber: ").append(toIndentedString(dsReferenceNumber)).append("\n");
    sb.append("    dsTransID: ").append(toIndentedString(dsTransID)).append("\n");
    sb.append("    dsURL: ").append(toIndentedString(dsURL)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    homePhone: ").append(toIndentedString(homePhone)).append("\n");
    sb.append("    mcc: ").append(toIndentedString(mcc)).append("\n");
    sb.append("    merchantCountryCode: ").append(toIndentedString(merchantCountryCode)).append("\n");
    sb.append("    merchantName: ").append(toIndentedString(merchantName)).append("\n");
    sb.append("    merchantRiskIndicator: ").append(toIndentedString(merchantRiskIndicator)).append("\n");
    sb.append("    messageCategory: ").append(toIndentedString(messageCategory)).append("\n");
    sb.append("    messageExtension: ").append(toIndentedString(messageExtension)).append("\n");
    sb.append("    mobilePhone: ").append(toIndentedString(mobilePhone)).append("\n");
    sb.append("    notificationURL: ").append(toIndentedString(notificationURL)).append("\n");
    sb.append("    payTokenInd: ").append(toIndentedString(payTokenInd)).append("\n");
    sb.append("    payTokenSource: ").append(toIndentedString(payTokenSource)).append("\n");
    sb.append("    purchaseAmount: ").append(toIndentedString(purchaseAmount)).append("\n");
    sb.append("    purchaseCurrency: ").append(toIndentedString(purchaseCurrency)).append("\n");
    sb.append("    purchaseDate: ").append(toIndentedString(purchaseDate)).append("\n");
    sb.append("    purchaseExponent: ").append(toIndentedString(purchaseExponent)).append("\n");
    sb.append("    purchaseInstalData: ").append(toIndentedString(purchaseInstalData)).append("\n");
    sb.append("    recurringExpiry: ").append(toIndentedString(recurringExpiry)).append("\n");
    sb.append("    recurringFrequency: ").append(toIndentedString(recurringFrequency)).append("\n");
    sb.append("    sdkAppID: ").append(toIndentedString(sdkAppID)).append("\n");
    sb.append("    sdkEncData: ").append(toIndentedString(sdkEncData)).append("\n");
    sb.append("    sdkEphemPubKey: ").append(toIndentedString(sdkEphemPubKey)).append("\n");
    sb.append("    sdkMaxTimeout: ").append(toIndentedString(sdkMaxTimeout)).append("\n");
    sb.append("    sdkReferenceNumber: ").append(toIndentedString(sdkReferenceNumber)).append("\n");
    sb.append("    sdkTransID: ").append(toIndentedString(sdkTransID)).append("\n");
    sb.append("    shipAddrCity: ").append(toIndentedString(shipAddrCity)).append("\n");
    sb.append("    shipAddrCountry: ").append(toIndentedString(shipAddrCountry)).append("\n");
    sb.append("    shipAddrLine1: ").append(toIndentedString(shipAddrLine1)).append("\n");
    sb.append("    shipAddrLine2: ").append(toIndentedString(shipAddrLine2)).append("\n");
    sb.append("    shipAddrLine3: ").append(toIndentedString(shipAddrLine3)).append("\n");
    sb.append("    shipAddrPostCode: ").append(toIndentedString(shipAddrPostCode)).append("\n");
    sb.append("    shipAddrState: ").append(toIndentedString(shipAddrState)).append("\n");
    sb.append("    threeDSCompInd: ").append(toIndentedString(threeDSCompInd)).append("\n");
    sb.append("    threeDSReqAuthMethodInd: ").append(toIndentedString(threeDSReqAuthMethodInd)).append("\n");
    sb.append("    threeDSRequestorAuthenticationInd: ").append(toIndentedString(threeDSRequestorAuthenticationInd)).append("\n");
    sb.append("    threeDSRequestorAuthenticationInfo: ").append(toIndentedString(threeDSRequestorAuthenticationInfo)).append("\n");
    sb.append("    threeDSRequestorChallengeInd: ").append(toIndentedString(threeDSRequestorChallengeInd)).append("\n");
    sb.append("    threeDSRequestorDecMaxTime: ").append(toIndentedString(threeDSRequestorDecMaxTime)).append("\n");
    sb.append("    threeDSRequestorDecReqInd: ").append(toIndentedString(threeDSRequestorDecReqInd)).append("\n");
    sb.append("    threeDSRequestorID: ").append(toIndentedString(threeDSRequestorID)).append("\n");
    sb.append("    threeDSRequestorName: ").append(toIndentedString(threeDSRequestorName)).append("\n");
    sb.append("    threeDSRequestorPriorAuthenticationInfo: ").append(toIndentedString(threeDSRequestorPriorAuthenticationInfo)).append("\n");
    sb.append("    threeDSRequestorURL: ").append(toIndentedString(threeDSRequestorURL)).append("\n");
    sb.append("    threeDSServerOperatorID: ").append(toIndentedString(threeDSServerOperatorID)).append("\n");
    sb.append("    threeDSServerRefNumber: ").append(toIndentedString(threeDSServerRefNumber)).append("\n");
    sb.append("    threeDSServerTransID: ").append(toIndentedString(threeDSServerTransID)).append("\n");
    sb.append("    threeDSServerURL: ").append(toIndentedString(threeDSServerURL)).append("\n");
    sb.append("    threeRIInd: ").append(toIndentedString(threeRIInd)).append("\n");
    sb.append("    transType: ").append(toIndentedString(transType)).append("\n");
    sb.append("    whiteListStatus: ").append(toIndentedString(whiteListStatus)).append("\n");
    sb.append("    whiteListStatusSource: ").append(toIndentedString(whiteListStatusSource)).append("\n");
    sb.append("    workPhone: ").append(toIndentedString(workPhone)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

