/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.opentech.acsemv3dsProxyApiClient.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * ConfirmWhitelistingResultsWebRequest
 */

public class ConfirmWhitelistingResultsWebRequest {
  @JsonProperty("acsTransactionId")
  private String acsTransactionId = null;

  @JsonProperty("cardNumber")
  private String cardNumber = null;

  @JsonProperty("whitelistingConfirmed")
  private Boolean whitelistingConfirmed = null;

  @JsonProperty("whitelistingResult")
  private String whitelistingResult = null;

  public ConfirmWhitelistingResultsWebRequest acsTransactionId(String acsTransactionId) {
    this.acsTransactionId = acsTransactionId;
    return this;
  }

   /**
   * Get acsTransactionId
   * @return acsTransactionId
  **/
  @ApiModelProperty(value = "")
  public String getAcsTransactionId() {
    return acsTransactionId;
  }

  public void setAcsTransactionId(String acsTransactionId) {
    this.acsTransactionId = acsTransactionId;
  }

  public ConfirmWhitelistingResultsWebRequest cardNumber(String cardNumber) {
    this.cardNumber = cardNumber;
    return this;
  }

   /**
   * Get cardNumber
   * @return cardNumber
  **/
  @ApiModelProperty(value = "")
  public String getCardNumber() {
    return cardNumber;
  }

  public void setCardNumber(String cardNumber) {
    this.cardNumber = cardNumber;
  }

  public ConfirmWhitelistingResultsWebRequest whitelistingConfirmed(Boolean whitelistingConfirmed) {
    this.whitelistingConfirmed = whitelistingConfirmed;
    return this;
  }

   /**
   * Get whitelistingConfirmed
   * @return whitelistingConfirmed
  **/
  @ApiModelProperty(value = "")
  public Boolean isWhitelistingConfirmed() {
    return whitelistingConfirmed;
  }

  public void setWhitelistingConfirmed(Boolean whitelistingConfirmed) {
    this.whitelistingConfirmed = whitelistingConfirmed;
  }

  public ConfirmWhitelistingResultsWebRequest whitelistingResult(String whitelistingResult) {
    this.whitelistingResult = whitelistingResult;
    return this;
  }

   /**
   * Get whitelistingResult
   * @return whitelistingResult
  **/
  @ApiModelProperty(value = "")
  public String getWhitelistingResult() {
    return whitelistingResult;
  }

  public void setWhitelistingResult(String whitelistingResult) {
    this.whitelistingResult = whitelistingResult;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConfirmWhitelistingResultsWebRequest confirmWhitelistingResultsWebRequest = (ConfirmWhitelistingResultsWebRequest) o;
    return Objects.equals(this.acsTransactionId, confirmWhitelistingResultsWebRequest.acsTransactionId) &&
        Objects.equals(this.cardNumber, confirmWhitelistingResultsWebRequest.cardNumber) &&
        Objects.equals(this.whitelistingConfirmed, confirmWhitelistingResultsWebRequest.whitelistingConfirmed) &&
        Objects.equals(this.whitelistingResult, confirmWhitelistingResultsWebRequest.whitelistingResult);
  }

  @Override
  public int hashCode() {
    return Objects.hash(acsTransactionId, cardNumber, whitelistingConfirmed, whitelistingResult);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConfirmWhitelistingResultsWebRequest {\n");
    
    sb.append("    acsTransactionId: ").append(toIndentedString(acsTransactionId)).append("\n");
    sb.append("    cardNumber: ").append(toIndentedString(cardNumber)).append("\n");
    sb.append("    whitelistingConfirmed: ").append(toIndentedString(whitelistingConfirmed)).append("\n");
    sb.append("    whitelistingResult: ").append(toIndentedString(whitelistingResult)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

