/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.opentech.acsemv3dsProxyApiClient.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.opentech.acsemv3dsProxyApiClient.model.AReq;
import com.opentech.acsemv3dsProxyApiClient.model.BrowserInfo;
import com.opentech.acsemv3dsProxyApiClient.model.TransactionInfo;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * DetectTransactionLanguageWebRequest
 */

public class DetectTransactionLanguageWebRequest {
  @JsonProperty("aReq")
  private AReq aReq = null;

  @JsonProperty("browserInfo")
  private BrowserInfo browserInfo = null;

  @JsonProperty("priorTransactionInfo")
  private TransactionInfo priorTransactionInfo = null;

  @JsonProperty("transactionInfo")
  private TransactionInfo transactionInfo = null;

  public DetectTransactionLanguageWebRequest aReq(AReq aReq) {
    this.aReq = aReq;
    return this;
  }

   /**
   * Get aReq
   * @return aReq
  **/
  @ApiModelProperty(value = "")
  public AReq getAReq() {
    return aReq;
  }

  public void setAReq(AReq aReq) {
    this.aReq = aReq;
  }

  public DetectTransactionLanguageWebRequest browserInfo(BrowserInfo browserInfo) {
    this.browserInfo = browserInfo;
    return this;
  }

   /**
   * Get browserInfo
   * @return browserInfo
  **/
  @ApiModelProperty(value = "")
  public BrowserInfo getBrowserInfo() {
    return browserInfo;
  }

  public void setBrowserInfo(BrowserInfo browserInfo) {
    this.browserInfo = browserInfo;
  }

  public DetectTransactionLanguageWebRequest priorTransactionInfo(TransactionInfo priorTransactionInfo) {
    this.priorTransactionInfo = priorTransactionInfo;
    return this;
  }

   /**
   * Get priorTransactionInfo
   * @return priorTransactionInfo
  **/
  @ApiModelProperty(value = "")
  public TransactionInfo getPriorTransactionInfo() {
    return priorTransactionInfo;
  }

  public void setPriorTransactionInfo(TransactionInfo priorTransactionInfo) {
    this.priorTransactionInfo = priorTransactionInfo;
  }

  public DetectTransactionLanguageWebRequest transactionInfo(TransactionInfo transactionInfo) {
    this.transactionInfo = transactionInfo;
    return this;
  }

   /**
   * Get transactionInfo
   * @return transactionInfo
  **/
  @ApiModelProperty(value = "")
  public TransactionInfo getTransactionInfo() {
    return transactionInfo;
  }

  public void setTransactionInfo(TransactionInfo transactionInfo) {
    this.transactionInfo = transactionInfo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DetectTransactionLanguageWebRequest detectTransactionLanguageWebRequest = (DetectTransactionLanguageWebRequest) o;
    return Objects.equals(this.aReq, detectTransactionLanguageWebRequest.aReq) &&
        Objects.equals(this.browserInfo, detectTransactionLanguageWebRequest.browserInfo) &&
        Objects.equals(this.priorTransactionInfo, detectTransactionLanguageWebRequest.priorTransactionInfo) &&
        Objects.equals(this.transactionInfo, detectTransactionLanguageWebRequest.transactionInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(aReq, browserInfo, priorTransactionInfo, transactionInfo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DetectTransactionLanguageWebRequest {\n");
    
    sb.append("    aReq: ").append(toIndentedString(aReq)).append("\n");
    sb.append("    browserInfo: ").append(toIndentedString(browserInfo)).append("\n");
    sb.append("    priorTransactionInfo: ").append(toIndentedString(priorTransactionInfo)).append("\n");
    sb.append("    transactionInfo: ").append(toIndentedString(transactionInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

