/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.opentech.acsemv3dsProxyApiClient.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.opentech.acsemv3dsProxyApiClient.model.AReq;
import com.opentech.acsemv3dsProxyApiClient.model.ThreeRIInfo;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * EvaluateAuthenticationWebRequest
 */

public class EvaluateAuthenticationWebRequest {
  @JsonProperty("aReq")
  private AReq aReq = null;

  @JsonProperty("threeRIInfo")
  private ThreeRIInfo threeRIInfo = null;

  public EvaluateAuthenticationWebRequest aReq(AReq aReq) {
    this.aReq = aReq;
    return this;
  }

   /**
   * Get aReq
   * @return aReq
  **/
  @ApiModelProperty(value = "")
  public AReq getAReq() {
    return aReq;
  }

  public void setAReq(AReq aReq) {
    this.aReq = aReq;
  }

  public EvaluateAuthenticationWebRequest threeRIInfo(ThreeRIInfo threeRIInfo) {
    this.threeRIInfo = threeRIInfo;
    return this;
  }

   /**
   * Get threeRIInfo
   * @return threeRIInfo
  **/
  @ApiModelProperty(value = "")
  public ThreeRIInfo getThreeRIInfo() {
    return threeRIInfo;
  }

  public void setThreeRIInfo(ThreeRIInfo threeRIInfo) {
    this.threeRIInfo = threeRIInfo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EvaluateAuthenticationWebRequest evaluateAuthenticationWebRequest = (EvaluateAuthenticationWebRequest) o;
    return Objects.equals(this.aReq, evaluateAuthenticationWebRequest.aReq) &&
        Objects.equals(this.threeRIInfo, evaluateAuthenticationWebRequest.threeRIInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(aReq, threeRIInfo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EvaluateAuthenticationWebRequest {\n");
    
    sb.append("    aReq: ").append(toIndentedString(aReq)).append("\n");
    sb.append("    threeRIInfo: ").append(toIndentedString(threeRIInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

