/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.opentech.acsemv3dsProxyApiClient.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.opentech.acsemv3dsProxyApiClient.model.CReq;
import com.opentech.acsemv3dsProxyApiClient.model.TransactionInfo;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * EvaluateChallengeStepAuthenticatorWebRequest
 */

public class EvaluateChallengeStepAuthenticatorWebRequest {
  @JsonProperty("authenticationName")
  private String authenticationName = null;

  @JsonProperty("cReq")
  private CReq cReq = null;

  @JsonProperty("cardNumber")
  private String cardNumber = null;

  @JsonProperty("challengeType")
  private String challengeType = null;

  @JsonProperty("challengeValue")
  private String challengeValue = null;

  @JsonProperty("transactionInfo")
  private TransactionInfo transactionInfo = null;

  public EvaluateChallengeStepAuthenticatorWebRequest authenticationName(String authenticationName) {
    this.authenticationName = authenticationName;
    return this;
  }

   /**
   * Get authenticationName
   * @return authenticationName
  **/
  @ApiModelProperty(value = "")
  public String getAuthenticationName() {
    return authenticationName;
  }

  public void setAuthenticationName(String authenticationName) {
    this.authenticationName = authenticationName;
  }

  public EvaluateChallengeStepAuthenticatorWebRequest cReq(CReq cReq) {
    this.cReq = cReq;
    return this;
  }

   /**
   * Get cReq
   * @return cReq
  **/
  @ApiModelProperty(value = "")
  public CReq getCReq() {
    return cReq;
  }

  public void setCReq(CReq cReq) {
    this.cReq = cReq;
  }

  public EvaluateChallengeStepAuthenticatorWebRequest cardNumber(String cardNumber) {
    this.cardNumber = cardNumber;
    return this;
  }

   /**
   * Get cardNumber
   * @return cardNumber
  **/
  @ApiModelProperty(value = "")
  public String getCardNumber() {
    return cardNumber;
  }

  public void setCardNumber(String cardNumber) {
    this.cardNumber = cardNumber;
  }

  public EvaluateChallengeStepAuthenticatorWebRequest challengeType(String challengeType) {
    this.challengeType = challengeType;
    return this;
  }

   /**
   * Get challengeType
   * @return challengeType
  **/
  @ApiModelProperty(value = "")
  public String getChallengeType() {
    return challengeType;
  }

  public void setChallengeType(String challengeType) {
    this.challengeType = challengeType;
  }

  public EvaluateChallengeStepAuthenticatorWebRequest challengeValue(String challengeValue) {
    this.challengeValue = challengeValue;
    return this;
  }

   /**
   * Get challengeValue
   * @return challengeValue
  **/
  @ApiModelProperty(value = "")
  public String getChallengeValue() {
    return challengeValue;
  }

  public void setChallengeValue(String challengeValue) {
    this.challengeValue = challengeValue;
  }

  public EvaluateChallengeStepAuthenticatorWebRequest transactionInfo(TransactionInfo transactionInfo) {
    this.transactionInfo = transactionInfo;
    return this;
  }

   /**
   * Get transactionInfo
   * @return transactionInfo
  **/
  @ApiModelProperty(value = "")
  public TransactionInfo getTransactionInfo() {
    return transactionInfo;
  }

  public void setTransactionInfo(TransactionInfo transactionInfo) {
    this.transactionInfo = transactionInfo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EvaluateChallengeStepAuthenticatorWebRequest evaluateChallengeStepAuthenticatorWebRequest = (EvaluateChallengeStepAuthenticatorWebRequest) o;
    return Objects.equals(this.authenticationName, evaluateChallengeStepAuthenticatorWebRequest.authenticationName) &&
        Objects.equals(this.cReq, evaluateChallengeStepAuthenticatorWebRequest.cReq) &&
        Objects.equals(this.cardNumber, evaluateChallengeStepAuthenticatorWebRequest.cardNumber) &&
        Objects.equals(this.challengeType, evaluateChallengeStepAuthenticatorWebRequest.challengeType) &&
        Objects.equals(this.challengeValue, evaluateChallengeStepAuthenticatorWebRequest.challengeValue) &&
        Objects.equals(this.transactionInfo, evaluateChallengeStepAuthenticatorWebRequest.transactionInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authenticationName, cReq, cardNumber, challengeType, challengeValue, transactionInfo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EvaluateChallengeStepAuthenticatorWebRequest {\n");
    
    sb.append("    authenticationName: ").append(toIndentedString(authenticationName)).append("\n");
    sb.append("    cReq: ").append(toIndentedString(cReq)).append("\n");
    sb.append("    cardNumber: ").append(toIndentedString(cardNumber)).append("\n");
    sb.append("    challengeType: ").append(toIndentedString(challengeType)).append("\n");
    sb.append("    challengeValue: ").append(toIndentedString(challengeValue)).append("\n");
    sb.append("    transactionInfo: ").append(toIndentedString(transactionInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

