/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.opentech.acsemv3dsProxyApiClient.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.opentech.acsemv3dsProxyApiClient.model.CReq;
import com.opentech.acsemv3dsProxyApiClient.model.TransactionInfo;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * EvaluateChallengeStepCMWebRequest
 */


public class EvaluateChallengeStepCMWebRequest {
  @JsonProperty("arrivalCondition")
  private String arrivalCondition = null;

  @JsonProperty("authenticationName")
  private String authenticationName = null;

  @JsonProperty("cReq")
  private CReq cReq = null;

  @JsonProperty("currStepId")
  private String currStepId = null;

  @JsonProperty("requestWhitelist")
  private Boolean requestWhitelist = null;

  @JsonProperty("transactionInfo")
  private TransactionInfo transactionInfo = null;

  public EvaluateChallengeStepCMWebRequest arrivalCondition(String arrivalCondition) {
    this.arrivalCondition = arrivalCondition;
    return this;
  }

   /**
   * Get arrivalCondition
   * @return arrivalCondition
  **/
  @Schema(description = "")
  public String getArrivalCondition() {
    return arrivalCondition;
  }

  public void setArrivalCondition(String arrivalCondition) {
    this.arrivalCondition = arrivalCondition;
  }

  public EvaluateChallengeStepCMWebRequest authenticationName(String authenticationName) {
    this.authenticationName = authenticationName;
    return this;
  }

   /**
   * Get authenticationName
   * @return authenticationName
  **/
  @Schema(description = "")
  public String getAuthenticationName() {
    return authenticationName;
  }

  public void setAuthenticationName(String authenticationName) {
    this.authenticationName = authenticationName;
  }

  public EvaluateChallengeStepCMWebRequest cReq(CReq cReq) {
    this.cReq = cReq;
    return this;
  }

   /**
   * Get cReq
   * @return cReq
  **/
  @Schema(description = "")
  public CReq getCReq() {
    return cReq;
  }

  public void setCReq(CReq cReq) {
    this.cReq = cReq;
  }

  public EvaluateChallengeStepCMWebRequest currStepId(String currStepId) {
    this.currStepId = currStepId;
    return this;
  }

   /**
   * Get currStepId
   * @return currStepId
  **/
  @Schema(description = "")
  public String getCurrStepId() {
    return currStepId;
  }

  public void setCurrStepId(String currStepId) {
    this.currStepId = currStepId;
  }

  public EvaluateChallengeStepCMWebRequest requestWhitelist(Boolean requestWhitelist) {
    this.requestWhitelist = requestWhitelist;
    return this;
  }

   /**
   * Get requestWhitelist
   * @return requestWhitelist
  **/
  @Schema(description = "")
  public Boolean isRequestWhitelist() {
    return requestWhitelist;
  }

  public void setRequestWhitelist(Boolean requestWhitelist) {
    this.requestWhitelist = requestWhitelist;
  }

  public EvaluateChallengeStepCMWebRequest transactionInfo(TransactionInfo transactionInfo) {
    this.transactionInfo = transactionInfo;
    return this;
  }

   /**
   * Get transactionInfo
   * @return transactionInfo
  **/
  @Schema(description = "")
  public TransactionInfo getTransactionInfo() {
    return transactionInfo;
  }

  public void setTransactionInfo(TransactionInfo transactionInfo) {
    this.transactionInfo = transactionInfo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EvaluateChallengeStepCMWebRequest evaluateChallengeStepCMWebRequest = (EvaluateChallengeStepCMWebRequest) o;
    return Objects.equals(this.arrivalCondition, evaluateChallengeStepCMWebRequest.arrivalCondition) &&
        Objects.equals(this.authenticationName, evaluateChallengeStepCMWebRequest.authenticationName) &&
        Objects.equals(this.cReq, evaluateChallengeStepCMWebRequest.cReq) &&
        Objects.equals(this.currStepId, evaluateChallengeStepCMWebRequest.currStepId) &&
        Objects.equals(this.requestWhitelist, evaluateChallengeStepCMWebRequest.requestWhitelist) &&
        Objects.equals(this.transactionInfo, evaluateChallengeStepCMWebRequest.transactionInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(arrivalCondition, authenticationName, cReq, currStepId, requestWhitelist, transactionInfo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EvaluateChallengeStepCMWebRequest {\n");
    
    sb.append("    arrivalCondition: ").append(toIndentedString(arrivalCondition)).append("\n");
    sb.append("    authenticationName: ").append(toIndentedString(authenticationName)).append("\n");
    sb.append("    cReq: ").append(toIndentedString(cReq)).append("\n");
    sb.append("    currStepId: ").append(toIndentedString(currStepId)).append("\n");
    sb.append("    requestWhitelist: ").append(toIndentedString(requestWhitelist)).append("\n");
    sb.append("    transactionInfo: ").append(toIndentedString(transactionInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
