/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.opentech.acsemv3dsProxyApiClient.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.opentech.acsemv3dsProxyApiClient.model.AppChallengeInfo;
import com.opentech.acsemv3dsProxyApiClient.model.BrowserChallengeInfo;
import com.opentech.acsemv3dsProxyApiClient.model.CResInfo;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * EvaluateChallengeStepCMWebResponse
 */

public class EvaluateChallengeStepCMWebResponse {
  @JsonProperty("appNextChallengeInfo")
  private AppChallengeInfo appNextChallengeInfo = null;

  @JsonProperty("browserNextChallengeInfo")
  private BrowserChallengeInfo browserNextChallengeInfo = null;

  @JsonProperty("cResInfo")
  private CResInfo cResInfo = null;

  /**
   * Gets or Sets challengeStatus
   */
  public enum ChallengeStatusEnum {
    ONGOING("ONGOING"),
    
    TERMINATED_WITH_SUCCESS("TERMINATED_WITH_SUCCESS"),
    
    TERMINATED_WITH_FAILURE("TERMINATED_WITH_FAILURE");

    private String value;

    ChallengeStatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ChallengeStatusEnum fromValue(String text) {
      for (ChallengeStatusEnum b : ChallengeStatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("challengeStatus")
  private ChallengeStatusEnum challengeStatus = null;

  @JsonProperty("nextStepId")
  private String nextStepId = null;

  public EvaluateChallengeStepCMWebResponse appNextChallengeInfo(AppChallengeInfo appNextChallengeInfo) {
    this.appNextChallengeInfo = appNextChallengeInfo;
    return this;
  }

   /**
   * Get appNextChallengeInfo
   * @return appNextChallengeInfo
  **/
  @ApiModelProperty(value = "")
  public AppChallengeInfo getAppNextChallengeInfo() {
    return appNextChallengeInfo;
  }

  public void setAppNextChallengeInfo(AppChallengeInfo appNextChallengeInfo) {
    this.appNextChallengeInfo = appNextChallengeInfo;
  }

  public EvaluateChallengeStepCMWebResponse browserNextChallengeInfo(BrowserChallengeInfo browserNextChallengeInfo) {
    this.browserNextChallengeInfo = browserNextChallengeInfo;
    return this;
  }

   /**
   * Get browserNextChallengeInfo
   * @return browserNextChallengeInfo
  **/
  @ApiModelProperty(value = "")
  public BrowserChallengeInfo getBrowserNextChallengeInfo() {
    return browserNextChallengeInfo;
  }

  public void setBrowserNextChallengeInfo(BrowserChallengeInfo browserNextChallengeInfo) {
    this.browserNextChallengeInfo = browserNextChallengeInfo;
  }

  public EvaluateChallengeStepCMWebResponse cResInfo(CResInfo cResInfo) {
    this.cResInfo = cResInfo;
    return this;
  }

   /**
   * Get cResInfo
   * @return cResInfo
  **/
  @ApiModelProperty(value = "")
  public CResInfo getCResInfo() {
    return cResInfo;
  }

  public void setCResInfo(CResInfo cResInfo) {
    this.cResInfo = cResInfo;
  }

  public EvaluateChallengeStepCMWebResponse challengeStatus(ChallengeStatusEnum challengeStatus) {
    this.challengeStatus = challengeStatus;
    return this;
  }

   /**
   * Get challengeStatus
   * @return challengeStatus
  **/
  @ApiModelProperty(value = "")
  public ChallengeStatusEnum getChallengeStatus() {
    return challengeStatus;
  }

  public void setChallengeStatus(ChallengeStatusEnum challengeStatus) {
    this.challengeStatus = challengeStatus;
  }

  public EvaluateChallengeStepCMWebResponse nextStepId(String nextStepId) {
    this.nextStepId = nextStepId;
    return this;
  }

   /**
   * Get nextStepId
   * @return nextStepId
  **/
  @ApiModelProperty(value = "")
  public String getNextStepId() {
    return nextStepId;
  }

  public void setNextStepId(String nextStepId) {
    this.nextStepId = nextStepId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EvaluateChallengeStepCMWebResponse evaluateChallengeStepCMWebResponse = (EvaluateChallengeStepCMWebResponse) o;
    return Objects.equals(this.appNextChallengeInfo, evaluateChallengeStepCMWebResponse.appNextChallengeInfo) &&
        Objects.equals(this.browserNextChallengeInfo, evaluateChallengeStepCMWebResponse.browserNextChallengeInfo) &&
        Objects.equals(this.cResInfo, evaluateChallengeStepCMWebResponse.cResInfo) &&
        Objects.equals(this.challengeStatus, evaluateChallengeStepCMWebResponse.challengeStatus) &&
        Objects.equals(this.nextStepId, evaluateChallengeStepCMWebResponse.nextStepId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(appNextChallengeInfo, browserNextChallengeInfo, cResInfo, challengeStatus, nextStepId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EvaluateChallengeStepCMWebResponse {\n");
    
    sb.append("    appNextChallengeInfo: ").append(toIndentedString(appNextChallengeInfo)).append("\n");
    sb.append("    browserNextChallengeInfo: ").append(toIndentedString(browserNextChallengeInfo)).append("\n");
    sb.append("    cResInfo: ").append(toIndentedString(cResInfo)).append("\n");
    sb.append("    challengeStatus: ").append(toIndentedString(challengeStatus)).append("\n");
    sb.append("    nextStepId: ").append(toIndentedString(nextStepId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

