/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.opentech.acsemv3dsProxyApiClient.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.opentech.acsemv3dsProxyApiClient.model.Extension;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * InitChallengeAuthenticatorWebResponse
 */

public class InitChallengeAuthenticatorWebResponse {
  @JsonProperty("extensions")
  private List<Extension> extensions = null;

  @JsonProperty("requestWhitelist")
  private Boolean requestWhitelist = null;

  @JsonProperty("result")
  private String result = null;

  public InitChallengeAuthenticatorWebResponse extensions(List<Extension> extensions) {
    this.extensions = extensions;
    return this;
  }

  public InitChallengeAuthenticatorWebResponse addExtensionsItem(Extension extensionsItem) {
    if (this.extensions == null) {
      this.extensions = new ArrayList<Extension>();
    }
    this.extensions.add(extensionsItem);
    return this;
  }

   /**
   * Get extensions
   * @return extensions
  **/
  @ApiModelProperty(value = "")
  public List<Extension> getExtensions() {
    return extensions;
  }

  public void setExtensions(List<Extension> extensions) {
    this.extensions = extensions;
  }

  public InitChallengeAuthenticatorWebResponse requestWhitelist(Boolean requestWhitelist) {
    this.requestWhitelist = requestWhitelist;
    return this;
  }

   /**
   * Get requestWhitelist
   * @return requestWhitelist
  **/
  @ApiModelProperty(value = "")
  public Boolean isRequestWhitelist() {
    return requestWhitelist;
  }

  public void setRequestWhitelist(Boolean requestWhitelist) {
    this.requestWhitelist = requestWhitelist;
  }

  public InitChallengeAuthenticatorWebResponse result(String result) {
    this.result = result;
    return this;
  }

   /**
   * Get result
   * @return result
  **/
  @ApiModelProperty(value = "")
  public String getResult() {
    return result;
  }

  public void setResult(String result) {
    this.result = result;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InitChallengeAuthenticatorWebResponse initChallengeAuthenticatorWebResponse = (InitChallengeAuthenticatorWebResponse) o;
    return Objects.equals(this.extensions, initChallengeAuthenticatorWebResponse.extensions) &&
        Objects.equals(this.requestWhitelist, initChallengeAuthenticatorWebResponse.requestWhitelist) &&
        Objects.equals(this.result, initChallengeAuthenticatorWebResponse.result);
  }

  @Override
  public int hashCode() {
    return Objects.hash(extensions, requestWhitelist, result);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InitChallengeAuthenticatorWebResponse {\n");
    
    sb.append("    extensions: ").append(toIndentedString(extensions)).append("\n");
    sb.append("    requestWhitelist: ").append(toIndentedString(requestWhitelist)).append("\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

