/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.opentech.acsemv3dsProxyApiClient.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.opentech.acsemv3dsProxyApiClient.model.TransactionInformation;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * PerformDecoupledAuthWebRequest
 */

public class PerformDecoupledAuthWebRequest {
  @JsonProperty("timeoutInMinutes")
  private Integer timeoutInMinutes = null;

  @JsonProperty("transactionInformation")
  private TransactionInformation transactionInformation = null;

  public PerformDecoupledAuthWebRequest timeoutInMinutes(Integer timeoutInMinutes) {
    this.timeoutInMinutes = timeoutInMinutes;
    return this;
  }

   /**
   * Get timeoutInMinutes
   * @return timeoutInMinutes
  **/
  @ApiModelProperty(value = "")
  public Integer getTimeoutInMinutes() {
    return timeoutInMinutes;
  }

  public void setTimeoutInMinutes(Integer timeoutInMinutes) {
    this.timeoutInMinutes = timeoutInMinutes;
  }

  public PerformDecoupledAuthWebRequest transactionInformation(TransactionInformation transactionInformation) {
    this.transactionInformation = transactionInformation;
    return this;
  }

   /**
   * Get transactionInformation
   * @return transactionInformation
  **/
  @ApiModelProperty(value = "")
  public TransactionInformation getTransactionInformation() {
    return transactionInformation;
  }

  public void setTransactionInformation(TransactionInformation transactionInformation) {
    this.transactionInformation = transactionInformation;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PerformDecoupledAuthWebRequest performDecoupledAuthWebRequest = (PerformDecoupledAuthWebRequest) o;
    return Objects.equals(this.timeoutInMinutes, performDecoupledAuthWebRequest.timeoutInMinutes) &&
        Objects.equals(this.transactionInformation, performDecoupledAuthWebRequest.transactionInformation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(timeoutInMinutes, transactionInformation);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PerformDecoupledAuthWebRequest {\n");
    
    sb.append("    timeoutInMinutes: ").append(toIndentedString(timeoutInMinutes)).append("\n");
    sb.append("    transactionInformation: ").append(toIndentedString(transactionInformation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

