/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.opentech.acsemv3dsProxyApiClient.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.opentech.acsemv3dsProxyApiClient.model.RReqInfo;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * PrepareAuthenticationCompletionWebRequest
 */

public class PrepareAuthenticationCompletionWebRequest {
  @JsonProperty("acsTransactionId")
  private String acsTransactionId = null;

  @JsonProperty("cardNumber")
  private String cardNumber = null;

  @JsonProperty("rReqInfo")
  private RReqInfo rReqInfo = null;

  @JsonProperty("whitelistConfirmed")
  private Boolean whitelistConfirmed = null;

  @JsonProperty("whitelistResultProposal")
  private String whitelistResultProposal = null;

  public PrepareAuthenticationCompletionWebRequest acsTransactionId(String acsTransactionId) {
    this.acsTransactionId = acsTransactionId;
    return this;
  }

   /**
   * Get acsTransactionId
   * @return acsTransactionId
  **/
  @ApiModelProperty(value = "")
  public String getAcsTransactionId() {
    return acsTransactionId;
  }

  public void setAcsTransactionId(String acsTransactionId) {
    this.acsTransactionId = acsTransactionId;
  }

  public PrepareAuthenticationCompletionWebRequest cardNumber(String cardNumber) {
    this.cardNumber = cardNumber;
    return this;
  }

   /**
   * Get cardNumber
   * @return cardNumber
  **/
  @ApiModelProperty(value = "")
  public String getCardNumber() {
    return cardNumber;
  }

  public void setCardNumber(String cardNumber) {
    this.cardNumber = cardNumber;
  }

  public PrepareAuthenticationCompletionWebRequest rReqInfo(RReqInfo rReqInfo) {
    this.rReqInfo = rReqInfo;
    return this;
  }

   /**
   * Get rReqInfo
   * @return rReqInfo
  **/
  @ApiModelProperty(value = "")
  public RReqInfo getRReqInfo() {
    return rReqInfo;
  }

  public void setRReqInfo(RReqInfo rReqInfo) {
    this.rReqInfo = rReqInfo;
  }

  public PrepareAuthenticationCompletionWebRequest whitelistConfirmed(Boolean whitelistConfirmed) {
    this.whitelistConfirmed = whitelistConfirmed;
    return this;
  }

   /**
   * Get whitelistConfirmed
   * @return whitelistConfirmed
  **/
  @ApiModelProperty(value = "")
  public Boolean isWhitelistConfirmed() {
    return whitelistConfirmed;
  }

  public void setWhitelistConfirmed(Boolean whitelistConfirmed) {
    this.whitelistConfirmed = whitelistConfirmed;
  }

  public PrepareAuthenticationCompletionWebRequest whitelistResultProposal(String whitelistResultProposal) {
    this.whitelistResultProposal = whitelistResultProposal;
    return this;
  }

   /**
   * Get whitelistResultProposal
   * @return whitelistResultProposal
  **/
  @ApiModelProperty(value = "")
  public String getWhitelistResultProposal() {
    return whitelistResultProposal;
  }

  public void setWhitelistResultProposal(String whitelistResultProposal) {
    this.whitelistResultProposal = whitelistResultProposal;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PrepareAuthenticationCompletionWebRequest prepareAuthenticationCompletionWebRequest = (PrepareAuthenticationCompletionWebRequest) o;
    return Objects.equals(this.acsTransactionId, prepareAuthenticationCompletionWebRequest.acsTransactionId) &&
        Objects.equals(this.cardNumber, prepareAuthenticationCompletionWebRequest.cardNumber) &&
        Objects.equals(this.rReqInfo, prepareAuthenticationCompletionWebRequest.rReqInfo) &&
        Objects.equals(this.whitelistConfirmed, prepareAuthenticationCompletionWebRequest.whitelistConfirmed) &&
        Objects.equals(this.whitelistResultProposal, prepareAuthenticationCompletionWebRequest.whitelistResultProposal);
  }

  @Override
  public int hashCode() {
    return Objects.hash(acsTransactionId, cardNumber, rReqInfo, whitelistConfirmed, whitelistResultProposal);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PrepareAuthenticationCompletionWebRequest {\n");
    
    sb.append("    acsTransactionId: ").append(toIndentedString(acsTransactionId)).append("\n");
    sb.append("    cardNumber: ").append(toIndentedString(cardNumber)).append("\n");
    sb.append("    rReqInfo: ").append(toIndentedString(rReqInfo)).append("\n");
    sb.append("    whitelistConfirmed: ").append(toIndentedString(whitelistConfirmed)).append("\n");
    sb.append("    whitelistResultProposal: ").append(toIndentedString(whitelistResultProposal)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

