/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.opentech.acsemv3dsProxyApiClient.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.opentech.acsemv3dsProxyApiClient.model.Extension;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * PrepareAuthenticationCompletionWebResponse
 */


public class PrepareAuthenticationCompletionWebResponse {
  @JsonProperty("cResExtensions")
  private List<Extension> cResExtensions = null;

  @JsonProperty("rReqExtensions")
  private List<Extension> rReqExtensions = null;

  @JsonProperty("whitelistResult")
  private String whitelistResult = null;

  public PrepareAuthenticationCompletionWebResponse cResExtensions(List<Extension> cResExtensions) {
    this.cResExtensions = cResExtensions;
    return this;
  }

  public PrepareAuthenticationCompletionWebResponse addCResExtensionsItem(Extension cResExtensionsItem) {
    if (this.cResExtensions == null) {
      this.cResExtensions = new ArrayList<Extension>();
    }
    this.cResExtensions.add(cResExtensionsItem);
    return this;
  }

   /**
   * Get cResExtensions
   * @return cResExtensions
  **/
  @Schema(description = "")
  public List<Extension> getCResExtensions() {
    return cResExtensions;
  }

  public void setCResExtensions(List<Extension> cResExtensions) {
    this.cResExtensions = cResExtensions;
  }

  public PrepareAuthenticationCompletionWebResponse rReqExtensions(List<Extension> rReqExtensions) {
    this.rReqExtensions = rReqExtensions;
    return this;
  }

  public PrepareAuthenticationCompletionWebResponse addRReqExtensionsItem(Extension rReqExtensionsItem) {
    if (this.rReqExtensions == null) {
      this.rReqExtensions = new ArrayList<Extension>();
    }
    this.rReqExtensions.add(rReqExtensionsItem);
    return this;
  }

   /**
   * Get rReqExtensions
   * @return rReqExtensions
  **/
  @Schema(description = "")
  public List<Extension> getRReqExtensions() {
    return rReqExtensions;
  }

  public void setRReqExtensions(List<Extension> rReqExtensions) {
    this.rReqExtensions = rReqExtensions;
  }

  public PrepareAuthenticationCompletionWebResponse whitelistResult(String whitelistResult) {
    this.whitelistResult = whitelistResult;
    return this;
  }

   /**
   * Get whitelistResult
   * @return whitelistResult
  **/
  @Schema(description = "")
  public String getWhitelistResult() {
    return whitelistResult;
  }

  public void setWhitelistResult(String whitelistResult) {
    this.whitelistResult = whitelistResult;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PrepareAuthenticationCompletionWebResponse prepareAuthenticationCompletionWebResponse = (PrepareAuthenticationCompletionWebResponse) o;
    return Objects.equals(this.cResExtensions, prepareAuthenticationCompletionWebResponse.cResExtensions) &&
        Objects.equals(this.rReqExtensions, prepareAuthenticationCompletionWebResponse.rReqExtensions) &&
        Objects.equals(this.whitelistResult, prepareAuthenticationCompletionWebResponse.whitelistResult);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cResExtensions, rReqExtensions, whitelistResult);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PrepareAuthenticationCompletionWebResponse {\n");
    
    sb.append("    cResExtensions: ").append(toIndentedString(cResExtensions)).append("\n");
    sb.append("    rReqExtensions: ").append(toIndentedString(rReqExtensions)).append("\n");
    sb.append("    whitelistResult: ").append(toIndentedString(whitelistResult)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
