/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.opentech.acsemv3dsProxyApiClient.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * RReqInfo
 */

public class RReqInfo {
  @JsonProperty("challengeCancel")
  private String challengeCancel = null;

  @JsonProperty("transactionStatus")
  private String transactionStatus = null;

  @JsonProperty("transactionStatusReason")
  private String transactionStatusReason = null;

  public RReqInfo challengeCancel(String challengeCancel) {
    this.challengeCancel = challengeCancel;
    return this;
  }

   /**
   * Get challengeCancel
   * @return challengeCancel
  **/
  @ApiModelProperty(value = "")
  public String getChallengeCancel() {
    return challengeCancel;
  }

  public void setChallengeCancel(String challengeCancel) {
    this.challengeCancel = challengeCancel;
  }

  public RReqInfo transactionStatus(String transactionStatus) {
    this.transactionStatus = transactionStatus;
    return this;
  }

   /**
   * Get transactionStatus
   * @return transactionStatus
  **/
  @ApiModelProperty(value = "")
  public String getTransactionStatus() {
    return transactionStatus;
  }

  public void setTransactionStatus(String transactionStatus) {
    this.transactionStatus = transactionStatus;
  }

  public RReqInfo transactionStatusReason(String transactionStatusReason) {
    this.transactionStatusReason = transactionStatusReason;
    return this;
  }

   /**
   * Get transactionStatusReason
   * @return transactionStatusReason
  **/
  @ApiModelProperty(value = "")
  public String getTransactionStatusReason() {
    return transactionStatusReason;
  }

  public void setTransactionStatusReason(String transactionStatusReason) {
    this.transactionStatusReason = transactionStatusReason;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RReqInfo rreqInfo = (RReqInfo) o;
    return Objects.equals(this.challengeCancel, rreqInfo.challengeCancel) &&
        Objects.equals(this.transactionStatus, rreqInfo.transactionStatus) &&
        Objects.equals(this.transactionStatusReason, rreqInfo.transactionStatusReason);
  }

  @Override
  public int hashCode() {
    return Objects.hash(challengeCancel, transactionStatus, transactionStatusReason);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RReqInfo {\n");
    
    sb.append("    challengeCancel: ").append(toIndentedString(challengeCancel)).append("\n");
    sb.append("    transactionStatus: ").append(toIndentedString(transactionStatus)).append("\n");
    sb.append("    transactionStatusReason: ").append(toIndentedString(transactionStatusReason)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

