/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.opentech.acsemv3dsProxyApiClient.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * ThreeDSRequestorAuthInfo
 */


public class ThreeDSRequestorAuthInfo {
  @JsonProperty("threeDSReqAuthData")
  private String threeDSReqAuthData = null;

  @JsonProperty("threeDSReqAuthMethod")
  private String threeDSReqAuthMethod = null;

  @JsonProperty("threeDSReqAuthTimestamp")
  private String threeDSReqAuthTimestamp = null;

  public ThreeDSRequestorAuthInfo threeDSReqAuthData(String threeDSReqAuthData) {
    this.threeDSReqAuthData = threeDSReqAuthData;
    return this;
  }

   /**
   * Get threeDSReqAuthData
   * @return threeDSReqAuthData
  **/
  @Schema(description = "")
  public String getThreeDSReqAuthData() {
    return threeDSReqAuthData;
  }

  public void setThreeDSReqAuthData(String threeDSReqAuthData) {
    this.threeDSReqAuthData = threeDSReqAuthData;
  }

  public ThreeDSRequestorAuthInfo threeDSReqAuthMethod(String threeDSReqAuthMethod) {
    this.threeDSReqAuthMethod = threeDSReqAuthMethod;
    return this;
  }

   /**
   * Get threeDSReqAuthMethod
   * @return threeDSReqAuthMethod
  **/
  @Schema(description = "")
  public String getThreeDSReqAuthMethod() {
    return threeDSReqAuthMethod;
  }

  public void setThreeDSReqAuthMethod(String threeDSReqAuthMethod) {
    this.threeDSReqAuthMethod = threeDSReqAuthMethod;
  }

  public ThreeDSRequestorAuthInfo threeDSReqAuthTimestamp(String threeDSReqAuthTimestamp) {
    this.threeDSReqAuthTimestamp = threeDSReqAuthTimestamp;
    return this;
  }

   /**
   * Get threeDSReqAuthTimestamp
   * @return threeDSReqAuthTimestamp
  **/
  @Schema(description = "")
  public String getThreeDSReqAuthTimestamp() {
    return threeDSReqAuthTimestamp;
  }

  public void setThreeDSReqAuthTimestamp(String threeDSReqAuthTimestamp) {
    this.threeDSReqAuthTimestamp = threeDSReqAuthTimestamp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ThreeDSRequestorAuthInfo threeDSRequestorAuthInfo = (ThreeDSRequestorAuthInfo) o;
    return Objects.equals(this.threeDSReqAuthData, threeDSRequestorAuthInfo.threeDSReqAuthData) &&
        Objects.equals(this.threeDSReqAuthMethod, threeDSRequestorAuthInfo.threeDSReqAuthMethod) &&
        Objects.equals(this.threeDSReqAuthTimestamp, threeDSRequestorAuthInfo.threeDSReqAuthTimestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(threeDSReqAuthData, threeDSReqAuthMethod, threeDSReqAuthTimestamp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ThreeDSRequestorAuthInfo {\n");
    
    sb.append("    threeDSReqAuthData: ").append(toIndentedString(threeDSReqAuthData)).append("\n");
    sb.append("    threeDSReqAuthMethod: ").append(toIndentedString(threeDSReqAuthMethod)).append("\n");
    sb.append("    threeDSReqAuthTimestamp: ").append(toIndentedString(threeDSReqAuthTimestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
