/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.opentech.acsemv3dsProxyApiClient.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * ThreeDSAcsRenderingType
 */

public class ThreeDSAcsRenderingType {
  @JsonProperty("acsInterface")
  private String acsInterface = null;

  @JsonProperty("acsUiTemplate")
  private String acsUiTemplate = null;

  public ThreeDSAcsRenderingType acsInterface(String acsInterface) {
    this.acsInterface = acsInterface;
    return this;
  }

   /**
   * Get acsInterface
   * @return acsInterface
  **/
  @ApiModelProperty(value = "")
  public String getAcsInterface() {
    return acsInterface;
  }

  public void setAcsInterface(String acsInterface) {
    this.acsInterface = acsInterface;
  }

  public ThreeDSAcsRenderingType acsUiTemplate(String acsUiTemplate) {
    this.acsUiTemplate = acsUiTemplate;
    return this;
  }

   /**
   * Get acsUiTemplate
   * @return acsUiTemplate
  **/
  @ApiModelProperty(value = "")
  public String getAcsUiTemplate() {
    return acsUiTemplate;
  }

  public void setAcsUiTemplate(String acsUiTemplate) {
    this.acsUiTemplate = acsUiTemplate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ThreeDSAcsRenderingType threeDSAcsRenderingType = (ThreeDSAcsRenderingType) o;
    return Objects.equals(this.acsInterface, threeDSAcsRenderingType.acsInterface) &&
        Objects.equals(this.acsUiTemplate, threeDSAcsRenderingType.acsUiTemplate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(acsInterface, acsUiTemplate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ThreeDSAcsRenderingType {\n");
    
    sb.append("    acsInterface: ").append(toIndentedString(acsInterface)).append("\n");
    sb.append("    acsUiTemplate: ").append(toIndentedString(acsUiTemplate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

