/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.opentech.acsemv3dsProxyApiClient.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * ThreeDSMerchantRiskIndicator
 */

public class ThreeDSMerchantRiskIndicator {
  @JsonProperty("deliveryEmailAddress")
  private String deliveryEmailAddress = null;

  @JsonProperty("deliveryTimeframe")
  private String deliveryTimeframe = null;

  @JsonProperty("giftCardAmount")
  private String giftCardAmount = null;

  @JsonProperty("giftCardCount")
  private String giftCardCount = null;

  @JsonProperty("giftCardCurr")
  private String giftCardCurr = null;

  @JsonProperty("preOrderDate")
  private String preOrderDate = null;

  @JsonProperty("preOrderPurchaseInd")
  private String preOrderPurchaseInd = null;

  @JsonProperty("reorderItemsInd")
  private String reorderItemsInd = null;

  @JsonProperty("shipIndicator")
  private String shipIndicator = null;

  public ThreeDSMerchantRiskIndicator deliveryEmailAddress(String deliveryEmailAddress) {
    this.deliveryEmailAddress = deliveryEmailAddress;
    return this;
  }

   /**
   * Get deliveryEmailAddress
   * @return deliveryEmailAddress
  **/
  @ApiModelProperty(value = "")
  public String getDeliveryEmailAddress() {
    return deliveryEmailAddress;
  }

  public void setDeliveryEmailAddress(String deliveryEmailAddress) {
    this.deliveryEmailAddress = deliveryEmailAddress;
  }

  public ThreeDSMerchantRiskIndicator deliveryTimeframe(String deliveryTimeframe) {
    this.deliveryTimeframe = deliveryTimeframe;
    return this;
  }

   /**
   * Get deliveryTimeframe
   * @return deliveryTimeframe
  **/
  @ApiModelProperty(value = "")
  public String getDeliveryTimeframe() {
    return deliveryTimeframe;
  }

  public void setDeliveryTimeframe(String deliveryTimeframe) {
    this.deliveryTimeframe = deliveryTimeframe;
  }

  public ThreeDSMerchantRiskIndicator giftCardAmount(String giftCardAmount) {
    this.giftCardAmount = giftCardAmount;
    return this;
  }

   /**
   * Get giftCardAmount
   * @return giftCardAmount
  **/
  @ApiModelProperty(value = "")
  public String getGiftCardAmount() {
    return giftCardAmount;
  }

  public void setGiftCardAmount(String giftCardAmount) {
    this.giftCardAmount = giftCardAmount;
  }

  public ThreeDSMerchantRiskIndicator giftCardCount(String giftCardCount) {
    this.giftCardCount = giftCardCount;
    return this;
  }

   /**
   * Get giftCardCount
   * @return giftCardCount
  **/
  @ApiModelProperty(value = "")
  public String getGiftCardCount() {
    return giftCardCount;
  }

  public void setGiftCardCount(String giftCardCount) {
    this.giftCardCount = giftCardCount;
  }

  public ThreeDSMerchantRiskIndicator giftCardCurr(String giftCardCurr) {
    this.giftCardCurr = giftCardCurr;
    return this;
  }

   /**
   * Get giftCardCurr
   * @return giftCardCurr
  **/
  @ApiModelProperty(value = "")
  public String getGiftCardCurr() {
    return giftCardCurr;
  }

  public void setGiftCardCurr(String giftCardCurr) {
    this.giftCardCurr = giftCardCurr;
  }

  public ThreeDSMerchantRiskIndicator preOrderDate(String preOrderDate) {
    this.preOrderDate = preOrderDate;
    return this;
  }

   /**
   * Get preOrderDate
   * @return preOrderDate
  **/
  @ApiModelProperty(value = "")
  public String getPreOrderDate() {
    return preOrderDate;
  }

  public void setPreOrderDate(String preOrderDate) {
    this.preOrderDate = preOrderDate;
  }

  public ThreeDSMerchantRiskIndicator preOrderPurchaseInd(String preOrderPurchaseInd) {
    this.preOrderPurchaseInd = preOrderPurchaseInd;
    return this;
  }

   /**
   * Get preOrderPurchaseInd
   * @return preOrderPurchaseInd
  **/
  @ApiModelProperty(value = "")
  public String getPreOrderPurchaseInd() {
    return preOrderPurchaseInd;
  }

  public void setPreOrderPurchaseInd(String preOrderPurchaseInd) {
    this.preOrderPurchaseInd = preOrderPurchaseInd;
  }

  public ThreeDSMerchantRiskIndicator reorderItemsInd(String reorderItemsInd) {
    this.reorderItemsInd = reorderItemsInd;
    return this;
  }

   /**
   * Get reorderItemsInd
   * @return reorderItemsInd
  **/
  @ApiModelProperty(value = "")
  public String getReorderItemsInd() {
    return reorderItemsInd;
  }

  public void setReorderItemsInd(String reorderItemsInd) {
    this.reorderItemsInd = reorderItemsInd;
  }

  public ThreeDSMerchantRiskIndicator shipIndicator(String shipIndicator) {
    this.shipIndicator = shipIndicator;
    return this;
  }

   /**
   * Get shipIndicator
   * @return shipIndicator
  **/
  @ApiModelProperty(value = "")
  public String getShipIndicator() {
    return shipIndicator;
  }

  public void setShipIndicator(String shipIndicator) {
    this.shipIndicator = shipIndicator;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ThreeDSMerchantRiskIndicator threeDSMerchantRiskIndicator = (ThreeDSMerchantRiskIndicator) o;
    return Objects.equals(this.deliveryEmailAddress, threeDSMerchantRiskIndicator.deliveryEmailAddress) &&
        Objects.equals(this.deliveryTimeframe, threeDSMerchantRiskIndicator.deliveryTimeframe) &&
        Objects.equals(this.giftCardAmount, threeDSMerchantRiskIndicator.giftCardAmount) &&
        Objects.equals(this.giftCardCount, threeDSMerchantRiskIndicator.giftCardCount) &&
        Objects.equals(this.giftCardCurr, threeDSMerchantRiskIndicator.giftCardCurr) &&
        Objects.equals(this.preOrderDate, threeDSMerchantRiskIndicator.preOrderDate) &&
        Objects.equals(this.preOrderPurchaseInd, threeDSMerchantRiskIndicator.preOrderPurchaseInd) &&
        Objects.equals(this.reorderItemsInd, threeDSMerchantRiskIndicator.reorderItemsInd) &&
        Objects.equals(this.shipIndicator, threeDSMerchantRiskIndicator.shipIndicator);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deliveryEmailAddress, deliveryTimeframe, giftCardAmount, giftCardCount, giftCardCurr, preOrderDate, preOrderPurchaseInd, reorderItemsInd, shipIndicator);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ThreeDSMerchantRiskIndicator {\n");
    
    sb.append("    deliveryEmailAddress: ").append(toIndentedString(deliveryEmailAddress)).append("\n");
    sb.append("    deliveryTimeframe: ").append(toIndentedString(deliveryTimeframe)).append("\n");
    sb.append("    giftCardAmount: ").append(toIndentedString(giftCardAmount)).append("\n");
    sb.append("    giftCardCount: ").append(toIndentedString(giftCardCount)).append("\n");
    sb.append("    giftCardCurr: ").append(toIndentedString(giftCardCurr)).append("\n");
    sb.append("    preOrderDate: ").append(toIndentedString(preOrderDate)).append("\n");
    sb.append("    preOrderPurchaseInd: ").append(toIndentedString(preOrderPurchaseInd)).append("\n");
    sb.append("    reorderItemsInd: ").append(toIndentedString(reorderItemsInd)).append("\n");
    sb.append("    shipIndicator: ").append(toIndentedString(shipIndicator)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

