/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.opentech.acsemv3dsProxyApiClient.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * ThreeDSRequestorPriorAuthInfo
 */

public class ThreeDSRequestorPriorAuthInfo {
  @JsonProperty("threeDSReqPriorAuthData")
  private Object threeDSReqPriorAuthData = null;

  @JsonProperty("threeDSReqPriorAuthMethod")
  private String threeDSReqPriorAuthMethod = null;

  @JsonProperty("threeDSReqPriorAuthTimestamp")
  private String threeDSReqPriorAuthTimestamp = null;

  @JsonProperty("threeDSReqPriorRef")
  private String threeDSReqPriorRef = null;

  public ThreeDSRequestorPriorAuthInfo threeDSReqPriorAuthData(Object threeDSReqPriorAuthData) {
    this.threeDSReqPriorAuthData = threeDSReqPriorAuthData;
    return this;
  }

   /**
   * Get threeDSReqPriorAuthData
   * @return threeDSReqPriorAuthData
  **/
  @ApiModelProperty(value = "")
  public Object getThreeDSReqPriorAuthData() {
    return threeDSReqPriorAuthData;
  }

  public void setThreeDSReqPriorAuthData(Object threeDSReqPriorAuthData) {
    this.threeDSReqPriorAuthData = threeDSReqPriorAuthData;
  }

  public ThreeDSRequestorPriorAuthInfo threeDSReqPriorAuthMethod(String threeDSReqPriorAuthMethod) {
    this.threeDSReqPriorAuthMethod = threeDSReqPriorAuthMethod;
    return this;
  }

   /**
   * Get threeDSReqPriorAuthMethod
   * @return threeDSReqPriorAuthMethod
  **/
  @ApiModelProperty(value = "")
  public String getThreeDSReqPriorAuthMethod() {
    return threeDSReqPriorAuthMethod;
  }

  public void setThreeDSReqPriorAuthMethod(String threeDSReqPriorAuthMethod) {
    this.threeDSReqPriorAuthMethod = threeDSReqPriorAuthMethod;
  }

  public ThreeDSRequestorPriorAuthInfo threeDSReqPriorAuthTimestamp(String threeDSReqPriorAuthTimestamp) {
    this.threeDSReqPriorAuthTimestamp = threeDSReqPriorAuthTimestamp;
    return this;
  }

   /**
   * Get threeDSReqPriorAuthTimestamp
   * @return threeDSReqPriorAuthTimestamp
  **/
  @ApiModelProperty(value = "")
  public String getThreeDSReqPriorAuthTimestamp() {
    return threeDSReqPriorAuthTimestamp;
  }

  public void setThreeDSReqPriorAuthTimestamp(String threeDSReqPriorAuthTimestamp) {
    this.threeDSReqPriorAuthTimestamp = threeDSReqPriorAuthTimestamp;
  }

  public ThreeDSRequestorPriorAuthInfo threeDSReqPriorRef(String threeDSReqPriorRef) {
    this.threeDSReqPriorRef = threeDSReqPriorRef;
    return this;
  }

   /**
   * Get threeDSReqPriorRef
   * @return threeDSReqPriorRef
  **/
  @ApiModelProperty(value = "")
  public String getThreeDSReqPriorRef() {
    return threeDSReqPriorRef;
  }

  public void setThreeDSReqPriorRef(String threeDSReqPriorRef) {
    this.threeDSReqPriorRef = threeDSReqPriorRef;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ThreeDSRequestorPriorAuthInfo threeDSRequestorPriorAuthInfo = (ThreeDSRequestorPriorAuthInfo) o;
    return Objects.equals(this.threeDSReqPriorAuthData, threeDSRequestorPriorAuthInfo.threeDSReqPriorAuthData) &&
        Objects.equals(this.threeDSReqPriorAuthMethod, threeDSRequestorPriorAuthInfo.threeDSReqPriorAuthMethod) &&
        Objects.equals(this.threeDSReqPriorAuthTimestamp, threeDSRequestorPriorAuthInfo.threeDSReqPriorAuthTimestamp) &&
        Objects.equals(this.threeDSReqPriorRef, threeDSRequestorPriorAuthInfo.threeDSReqPriorRef);
  }

  @Override
  public int hashCode() {
    return Objects.hash(threeDSReqPriorAuthData, threeDSReqPriorAuthMethod, threeDSReqPriorAuthTimestamp, threeDSReqPriorRef);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ThreeDSRequestorPriorAuthInfo {\n");
    
    sb.append("    threeDSReqPriorAuthData: ").append(toIndentedString(threeDSReqPriorAuthData)).append("\n");
    sb.append("    threeDSReqPriorAuthMethod: ").append(toIndentedString(threeDSReqPriorAuthMethod)).append("\n");
    sb.append("    threeDSReqPriorAuthTimestamp: ").append(toIndentedString(threeDSReqPriorAuthTimestamp)).append("\n");
    sb.append("    threeDSReqPriorRef: ").append(toIndentedString(threeDSReqPriorRef)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

