/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.opentech.acsemv3dsProxyApiClient.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * ThreeDSCardholderAccountInfo
 */


public class ThreeDSCardholderAccountInfo {
  @JsonProperty("chAccAgeInd")
  private String chAccAgeInd = null;

  @JsonProperty("chAccChange")
  private String chAccChange = null;

  @JsonProperty("chAccChangeInd")
  private String chAccChangeInd = null;

  @JsonProperty("chAccDate")
  private String chAccDate = null;

  @JsonProperty("chAccPwChange")
  private String chAccPwChange = null;

  @JsonProperty("chAccPwChangeInd")
  private String chAccPwChangeInd = null;

  @JsonProperty("nbPurchaseAccount")
  private String nbPurchaseAccount = null;

  @JsonProperty("paymentAccAge")
  private String paymentAccAge = null;

  @JsonProperty("paymentAccInd")
  private String paymentAccInd = null;

  @JsonProperty("provisionAttemptsDay")
  private String provisionAttemptsDay = null;

  @JsonProperty("shipAddressUsage")
  private String shipAddressUsage = null;

  @JsonProperty("shipAddressUsageInd")
  private String shipAddressUsageInd = null;

  @JsonProperty("shipNameIndicator")
  private String shipNameIndicator = null;

  @JsonProperty("suspiciousAccActivity")
  private String suspiciousAccActivity = null;

  @JsonProperty("txnActivityDay")
  private String txnActivityDay = null;

  @JsonProperty("txnActivityYear")
  private String txnActivityYear = null;

  public ThreeDSCardholderAccountInfo chAccAgeInd(String chAccAgeInd) {
    this.chAccAgeInd = chAccAgeInd;
    return this;
  }

   /**
   * Get chAccAgeInd
   * @return chAccAgeInd
  **/
  @Schema(description = "")
  public String getChAccAgeInd() {
    return chAccAgeInd;
  }

  public void setChAccAgeInd(String chAccAgeInd) {
    this.chAccAgeInd = chAccAgeInd;
  }

  public ThreeDSCardholderAccountInfo chAccChange(String chAccChange) {
    this.chAccChange = chAccChange;
    return this;
  }

   /**
   * Get chAccChange
   * @return chAccChange
  **/
  @Schema(description = "")
  public String getChAccChange() {
    return chAccChange;
  }

  public void setChAccChange(String chAccChange) {
    this.chAccChange = chAccChange;
  }

  public ThreeDSCardholderAccountInfo chAccChangeInd(String chAccChangeInd) {
    this.chAccChangeInd = chAccChangeInd;
    return this;
  }

   /**
   * Get chAccChangeInd
   * @return chAccChangeInd
  **/
  @Schema(description = "")
  public String getChAccChangeInd() {
    return chAccChangeInd;
  }

  public void setChAccChangeInd(String chAccChangeInd) {
    this.chAccChangeInd = chAccChangeInd;
  }

  public ThreeDSCardholderAccountInfo chAccDate(String chAccDate) {
    this.chAccDate = chAccDate;
    return this;
  }

   /**
   * Get chAccDate
   * @return chAccDate
  **/
  @Schema(description = "")
  public String getChAccDate() {
    return chAccDate;
  }

  public void setChAccDate(String chAccDate) {
    this.chAccDate = chAccDate;
  }

  public ThreeDSCardholderAccountInfo chAccPwChange(String chAccPwChange) {
    this.chAccPwChange = chAccPwChange;
    return this;
  }

   /**
   * Get chAccPwChange
   * @return chAccPwChange
  **/
  @Schema(description = "")
  public String getChAccPwChange() {
    return chAccPwChange;
  }

  public void setChAccPwChange(String chAccPwChange) {
    this.chAccPwChange = chAccPwChange;
  }

  public ThreeDSCardholderAccountInfo chAccPwChangeInd(String chAccPwChangeInd) {
    this.chAccPwChangeInd = chAccPwChangeInd;
    return this;
  }

   /**
   * Get chAccPwChangeInd
   * @return chAccPwChangeInd
  **/
  @Schema(description = "")
  public String getChAccPwChangeInd() {
    return chAccPwChangeInd;
  }

  public void setChAccPwChangeInd(String chAccPwChangeInd) {
    this.chAccPwChangeInd = chAccPwChangeInd;
  }

  public ThreeDSCardholderAccountInfo nbPurchaseAccount(String nbPurchaseAccount) {
    this.nbPurchaseAccount = nbPurchaseAccount;
    return this;
  }

   /**
   * Get nbPurchaseAccount
   * @return nbPurchaseAccount
  **/
  @Schema(description = "")
  public String getNbPurchaseAccount() {
    return nbPurchaseAccount;
  }

  public void setNbPurchaseAccount(String nbPurchaseAccount) {
    this.nbPurchaseAccount = nbPurchaseAccount;
  }

  public ThreeDSCardholderAccountInfo paymentAccAge(String paymentAccAge) {
    this.paymentAccAge = paymentAccAge;
    return this;
  }

   /**
   * Get paymentAccAge
   * @return paymentAccAge
  **/
  @Schema(description = "")
  public String getPaymentAccAge() {
    return paymentAccAge;
  }

  public void setPaymentAccAge(String paymentAccAge) {
    this.paymentAccAge = paymentAccAge;
  }

  public ThreeDSCardholderAccountInfo paymentAccInd(String paymentAccInd) {
    this.paymentAccInd = paymentAccInd;
    return this;
  }

   /**
   * Get paymentAccInd
   * @return paymentAccInd
  **/
  @Schema(description = "")
  public String getPaymentAccInd() {
    return paymentAccInd;
  }

  public void setPaymentAccInd(String paymentAccInd) {
    this.paymentAccInd = paymentAccInd;
  }

  public ThreeDSCardholderAccountInfo provisionAttemptsDay(String provisionAttemptsDay) {
    this.provisionAttemptsDay = provisionAttemptsDay;
    return this;
  }

   /**
   * Get provisionAttemptsDay
   * @return provisionAttemptsDay
  **/
  @Schema(description = "")
  public String getProvisionAttemptsDay() {
    return provisionAttemptsDay;
  }

  public void setProvisionAttemptsDay(String provisionAttemptsDay) {
    this.provisionAttemptsDay = provisionAttemptsDay;
  }

  public ThreeDSCardholderAccountInfo shipAddressUsage(String shipAddressUsage) {
    this.shipAddressUsage = shipAddressUsage;
    return this;
  }

   /**
   * Get shipAddressUsage
   * @return shipAddressUsage
  **/
  @Schema(description = "")
  public String getShipAddressUsage() {
    return shipAddressUsage;
  }

  public void setShipAddressUsage(String shipAddressUsage) {
    this.shipAddressUsage = shipAddressUsage;
  }

  public ThreeDSCardholderAccountInfo shipAddressUsageInd(String shipAddressUsageInd) {
    this.shipAddressUsageInd = shipAddressUsageInd;
    return this;
  }

   /**
   * Get shipAddressUsageInd
   * @return shipAddressUsageInd
  **/
  @Schema(description = "")
  public String getShipAddressUsageInd() {
    return shipAddressUsageInd;
  }

  public void setShipAddressUsageInd(String shipAddressUsageInd) {
    this.shipAddressUsageInd = shipAddressUsageInd;
  }

  public ThreeDSCardholderAccountInfo shipNameIndicator(String shipNameIndicator) {
    this.shipNameIndicator = shipNameIndicator;
    return this;
  }

   /**
   * Get shipNameIndicator
   * @return shipNameIndicator
  **/
  @Schema(description = "")
  public String getShipNameIndicator() {
    return shipNameIndicator;
  }

  public void setShipNameIndicator(String shipNameIndicator) {
    this.shipNameIndicator = shipNameIndicator;
  }

  public ThreeDSCardholderAccountInfo suspiciousAccActivity(String suspiciousAccActivity) {
    this.suspiciousAccActivity = suspiciousAccActivity;
    return this;
  }

   /**
   * Get suspiciousAccActivity
   * @return suspiciousAccActivity
  **/
  @Schema(description = "")
  public String getSuspiciousAccActivity() {
    return suspiciousAccActivity;
  }

  public void setSuspiciousAccActivity(String suspiciousAccActivity) {
    this.suspiciousAccActivity = suspiciousAccActivity;
  }

  public ThreeDSCardholderAccountInfo txnActivityDay(String txnActivityDay) {
    this.txnActivityDay = txnActivityDay;
    return this;
  }

   /**
   * Get txnActivityDay
   * @return txnActivityDay
  **/
  @Schema(description = "")
  public String getTxnActivityDay() {
    return txnActivityDay;
  }

  public void setTxnActivityDay(String txnActivityDay) {
    this.txnActivityDay = txnActivityDay;
  }

  public ThreeDSCardholderAccountInfo txnActivityYear(String txnActivityYear) {
    this.txnActivityYear = txnActivityYear;
    return this;
  }

   /**
   * Get txnActivityYear
   * @return txnActivityYear
  **/
  @Schema(description = "")
  public String getTxnActivityYear() {
    return txnActivityYear;
  }

  public void setTxnActivityYear(String txnActivityYear) {
    this.txnActivityYear = txnActivityYear;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ThreeDSCardholderAccountInfo threeDSCardholderAccountInfo = (ThreeDSCardholderAccountInfo) o;
    return Objects.equals(this.chAccAgeInd, threeDSCardholderAccountInfo.chAccAgeInd) &&
        Objects.equals(this.chAccChange, threeDSCardholderAccountInfo.chAccChange) &&
        Objects.equals(this.chAccChangeInd, threeDSCardholderAccountInfo.chAccChangeInd) &&
        Objects.equals(this.chAccDate, threeDSCardholderAccountInfo.chAccDate) &&
        Objects.equals(this.chAccPwChange, threeDSCardholderAccountInfo.chAccPwChange) &&
        Objects.equals(this.chAccPwChangeInd, threeDSCardholderAccountInfo.chAccPwChangeInd) &&
        Objects.equals(this.nbPurchaseAccount, threeDSCardholderAccountInfo.nbPurchaseAccount) &&
        Objects.equals(this.paymentAccAge, threeDSCardholderAccountInfo.paymentAccAge) &&
        Objects.equals(this.paymentAccInd, threeDSCardholderAccountInfo.paymentAccInd) &&
        Objects.equals(this.provisionAttemptsDay, threeDSCardholderAccountInfo.provisionAttemptsDay) &&
        Objects.equals(this.shipAddressUsage, threeDSCardholderAccountInfo.shipAddressUsage) &&
        Objects.equals(this.shipAddressUsageInd, threeDSCardholderAccountInfo.shipAddressUsageInd) &&
        Objects.equals(this.shipNameIndicator, threeDSCardholderAccountInfo.shipNameIndicator) &&
        Objects.equals(this.suspiciousAccActivity, threeDSCardholderAccountInfo.suspiciousAccActivity) &&
        Objects.equals(this.txnActivityDay, threeDSCardholderAccountInfo.txnActivityDay) &&
        Objects.equals(this.txnActivityYear, threeDSCardholderAccountInfo.txnActivityYear);
  }

  @Override
  public int hashCode() {
    return Objects.hash(chAccAgeInd, chAccChange, chAccChangeInd, chAccDate, chAccPwChange, chAccPwChangeInd, nbPurchaseAccount, paymentAccAge, paymentAccInd, provisionAttemptsDay, shipAddressUsage, shipAddressUsageInd, shipNameIndicator, suspiciousAccActivity, txnActivityDay, txnActivityYear);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ThreeDSCardholderAccountInfo {\n");
    
    sb.append("    chAccAgeInd: ").append(toIndentedString(chAccAgeInd)).append("\n");
    sb.append("    chAccChange: ").append(toIndentedString(chAccChange)).append("\n");
    sb.append("    chAccChangeInd: ").append(toIndentedString(chAccChangeInd)).append("\n");
    sb.append("    chAccDate: ").append(toIndentedString(chAccDate)).append("\n");
    sb.append("    chAccPwChange: ").append(toIndentedString(chAccPwChange)).append("\n");
    sb.append("    chAccPwChangeInd: ").append(toIndentedString(chAccPwChangeInd)).append("\n");
    sb.append("    nbPurchaseAccount: ").append(toIndentedString(nbPurchaseAccount)).append("\n");
    sb.append("    paymentAccAge: ").append(toIndentedString(paymentAccAge)).append("\n");
    sb.append("    paymentAccInd: ").append(toIndentedString(paymentAccInd)).append("\n");
    sb.append("    provisionAttemptsDay: ").append(toIndentedString(provisionAttemptsDay)).append("\n");
    sb.append("    shipAddressUsage: ").append(toIndentedString(shipAddressUsage)).append("\n");
    sb.append("    shipAddressUsageInd: ").append(toIndentedString(shipAddressUsageInd)).append("\n");
    sb.append("    shipNameIndicator: ").append(toIndentedString(shipNameIndicator)).append("\n");
    sb.append("    suspiciousAccActivity: ").append(toIndentedString(suspiciousAccActivity)).append("\n");
    sb.append("    txnActivityDay: ").append(toIndentedString(txnActivityDay)).append("\n");
    sb.append("    txnActivityYear: ").append(toIndentedString(txnActivityYear)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
