/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.opentech.acsemv3dsProxyApiClient.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * ThreeDSSdkRenderingOptions
 */


public class ThreeDSSdkRenderingOptions {
  @JsonProperty("sdkInterface")
  private String sdkInterface = null;

  @JsonProperty("sdkUiType")
  private List<String> sdkUiType = null;

  public ThreeDSSdkRenderingOptions sdkInterface(String sdkInterface) {
    this.sdkInterface = sdkInterface;
    return this;
  }

   /**
   * Get sdkInterface
   * @return sdkInterface
  **/
  @Schema(description = "")
  public String getSdkInterface() {
    return sdkInterface;
  }

  public void setSdkInterface(String sdkInterface) {
    this.sdkInterface = sdkInterface;
  }

  public ThreeDSSdkRenderingOptions sdkUiType(List<String> sdkUiType) {
    this.sdkUiType = sdkUiType;
    return this;
  }

  public ThreeDSSdkRenderingOptions addSdkUiTypeItem(String sdkUiTypeItem) {
    if (this.sdkUiType == null) {
      this.sdkUiType = new ArrayList<String>();
    }
    this.sdkUiType.add(sdkUiTypeItem);
    return this;
  }

   /**
   * Get sdkUiType
   * @return sdkUiType
  **/
  @Schema(description = "")
  public List<String> getSdkUiType() {
    return sdkUiType;
  }

  public void setSdkUiType(List<String> sdkUiType) {
    this.sdkUiType = sdkUiType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ThreeDSSdkRenderingOptions threeDSSdkRenderingOptions = (ThreeDSSdkRenderingOptions) o;
    return Objects.equals(this.sdkInterface, threeDSSdkRenderingOptions.sdkInterface) &&
        Objects.equals(this.sdkUiType, threeDSSdkRenderingOptions.sdkUiType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sdkInterface, sdkUiType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ThreeDSSdkRenderingOptions {\n");
    
    sb.append("    sdkInterface: ").append(toIndentedString(sdkInterface)).append("\n");
    sb.append("    sdkUiType: ").append(toIndentedString(sdkUiType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
