/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.opentech.acsemv3dsProxyApiClient.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.opentech.acsemv3dsProxyApiClient.model.ThreeDSAcsRenderingType;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Date;

/**
 * TransactionInfo
 */

public class TransactionInfo {
  @JsonProperty("aav")
  private String aav = null;

  @JsonProperty("acsMaxChallenges")
  private Integer acsMaxChallenges = null;

  @JsonProperty("acsRenderingType")
  private ThreeDSAcsRenderingType acsRenderingType = null;

  @JsonProperty("acsTransactionId")
  private String acsTransactionId = null;

  @JsonProperty("authenticationMethod")
  private String authenticationMethod = null;

  @JsonProperty("authenticationName")
  private String authenticationName = null;

  @JsonProperty("authenticationType")
  private String authenticationType = null;

  @JsonProperty("binRangeId")
  private String binRangeId = null;

  @JsonProperty("cRes")
  private byte[] cRes = null;

  @JsonProperty("completionDate")
  private Date completionDate = null;

  @JsonProperty("creationDate")
  private Date creationDate = null;

  @JsonProperty("currentStepId")
  private String currentStepId = null;

  @JsonProperty("deviceChannel")
  private String deviceChannel = null;

  @JsonProperty("dsTransactionId")
  private String dsTransactionId = null;

  @JsonProperty("dsUrl")
  private String dsUrl = null;

  @JsonProperty("eci")
  private String eci = null;

  @JsonProperty("instalment")
  private Boolean instalment = null;

  @JsonProperty("interactionCounter")
  private Integer interactionCounter = null;

  @JsonProperty("issuerCode")
  private String issuerCode = null;

  @JsonProperty("messageCategory")
  private String messageCategory = null;

  @JsonProperty("parentTransactionId")
  private String parentTransactionId = null;

  @JsonProperty("processingStep")
  private String processingStep = null;

  @JsonProperty("recurring")
  private Boolean recurring = null;

  @JsonProperty("sdkTransactionId")
  private String sdkTransactionId = null;

  @JsonProperty("secureVersion")
  private String secureVersion = null;

  @JsonProperty("threedsServerTransactionId")
  private String threedsServerTransactionId = null;

  @JsonProperty("transactionStatus")
  private String transactionStatus = null;

  @JsonProperty("validationReason")
  private String validationReason = null;

  public TransactionInfo aav(String aav) {
    this.aav = aav;
    return this;
  }

   /**
   * Get aav
   * @return aav
  **/
  @ApiModelProperty(value = "")
  public String getAav() {
    return aav;
  }

  public void setAav(String aav) {
    this.aav = aav;
  }

  public TransactionInfo acsMaxChallenges(Integer acsMaxChallenges) {
    this.acsMaxChallenges = acsMaxChallenges;
    return this;
  }

   /**
   * Get acsMaxChallenges
   * @return acsMaxChallenges
  **/
  @ApiModelProperty(value = "")
  public Integer getAcsMaxChallenges() {
    return acsMaxChallenges;
  }

  public void setAcsMaxChallenges(Integer acsMaxChallenges) {
    this.acsMaxChallenges = acsMaxChallenges;
  }

  public TransactionInfo acsRenderingType(ThreeDSAcsRenderingType acsRenderingType) {
    this.acsRenderingType = acsRenderingType;
    return this;
  }

   /**
   * Get acsRenderingType
   * @return acsRenderingType
  **/
  @ApiModelProperty(value = "")
  public ThreeDSAcsRenderingType getAcsRenderingType() {
    return acsRenderingType;
  }

  public void setAcsRenderingType(ThreeDSAcsRenderingType acsRenderingType) {
    this.acsRenderingType = acsRenderingType;
  }

  public TransactionInfo acsTransactionId(String acsTransactionId) {
    this.acsTransactionId = acsTransactionId;
    return this;
  }

   /**
   * Get acsTransactionId
   * @return acsTransactionId
  **/
  @ApiModelProperty(value = "")
  public String getAcsTransactionId() {
    return acsTransactionId;
  }

  public void setAcsTransactionId(String acsTransactionId) {
    this.acsTransactionId = acsTransactionId;
  }

  public TransactionInfo authenticationMethod(String authenticationMethod) {
    this.authenticationMethod = authenticationMethod;
    return this;
  }

   /**
   * Get authenticationMethod
   * @return authenticationMethod
  **/
  @ApiModelProperty(value = "")
  public String getAuthenticationMethod() {
    return authenticationMethod;
  }

  public void setAuthenticationMethod(String authenticationMethod) {
    this.authenticationMethod = authenticationMethod;
  }

  public TransactionInfo authenticationName(String authenticationName) {
    this.authenticationName = authenticationName;
    return this;
  }

   /**
   * Get authenticationName
   * @return authenticationName
  **/
  @ApiModelProperty(value = "")
  public String getAuthenticationName() {
    return authenticationName;
  }

  public void setAuthenticationName(String authenticationName) {
    this.authenticationName = authenticationName;
  }

  public TransactionInfo authenticationType(String authenticationType) {
    this.authenticationType = authenticationType;
    return this;
  }

   /**
   * Get authenticationType
   * @return authenticationType
  **/
  @ApiModelProperty(value = "")
  public String getAuthenticationType() {
    return authenticationType;
  }

  public void setAuthenticationType(String authenticationType) {
    this.authenticationType = authenticationType;
  }

  public TransactionInfo binRangeId(String binRangeId) {
    this.binRangeId = binRangeId;
    return this;
  }

   /**
   * Get binRangeId
   * @return binRangeId
  **/
  @ApiModelProperty(value = "")
  public String getBinRangeId() {
    return binRangeId;
  }

  public void setBinRangeId(String binRangeId) {
    this.binRangeId = binRangeId;
  }

  public TransactionInfo cRes(byte[] cRes) {
    this.cRes = cRes;
    return this;
  }

   /**
   * Get cRes
   * @return cRes
  **/
  @ApiModelProperty(value = "")
  public byte[] getCRes() {
    return cRes;
  }

  public void setCRes(byte[] cRes) {
    this.cRes = cRes;
  }

  public TransactionInfo completionDate(Date completionDate) {
    this.completionDate = completionDate;
    return this;
  }

   /**
   * Get completionDate
   * @return completionDate
  **/
  @ApiModelProperty(value = "")
  public Date getCompletionDate() {
    return completionDate;
  }

  public void setCompletionDate(Date completionDate) {
    this.completionDate = completionDate;
  }

  public TransactionInfo creationDate(Date creationDate) {
    this.creationDate = creationDate;
    return this;
  }

   /**
   * Get creationDate
   * @return creationDate
  **/
  @ApiModelProperty(value = "")
  public Date getCreationDate() {
    return creationDate;
  }

  public void setCreationDate(Date creationDate) {
    this.creationDate = creationDate;
  }

  public TransactionInfo currentStepId(String currentStepId) {
    this.currentStepId = currentStepId;
    return this;
  }

   /**
   * Get currentStepId
   * @return currentStepId
  **/
  @ApiModelProperty(value = "")
  public String getCurrentStepId() {
    return currentStepId;
  }

  public void setCurrentStepId(String currentStepId) {
    this.currentStepId = currentStepId;
  }

  public TransactionInfo deviceChannel(String deviceChannel) {
    this.deviceChannel = deviceChannel;
    return this;
  }

   /**
   * Get deviceChannel
   * @return deviceChannel
  **/
  @ApiModelProperty(value = "")
  public String getDeviceChannel() {
    return deviceChannel;
  }

  public void setDeviceChannel(String deviceChannel) {
    this.deviceChannel = deviceChannel;
  }

  public TransactionInfo dsTransactionId(String dsTransactionId) {
    this.dsTransactionId = dsTransactionId;
    return this;
  }

   /**
   * Get dsTransactionId
   * @return dsTransactionId
  **/
  @ApiModelProperty(value = "")
  public String getDsTransactionId() {
    return dsTransactionId;
  }

  public void setDsTransactionId(String dsTransactionId) {
    this.dsTransactionId = dsTransactionId;
  }

  public TransactionInfo dsUrl(String dsUrl) {
    this.dsUrl = dsUrl;
    return this;
  }

   /**
   * Get dsUrl
   * @return dsUrl
  **/
  @ApiModelProperty(value = "")
  public String getDsUrl() {
    return dsUrl;
  }

  public void setDsUrl(String dsUrl) {
    this.dsUrl = dsUrl;
  }

  public TransactionInfo eci(String eci) {
    this.eci = eci;
    return this;
  }

   /**
   * Get eci
   * @return eci
  **/
  @ApiModelProperty(value = "")
  public String getEci() {
    return eci;
  }

  public void setEci(String eci) {
    this.eci = eci;
  }

  public TransactionInfo instalment(Boolean instalment) {
    this.instalment = instalment;
    return this;
  }

   /**
   * Get instalment
   * @return instalment
  **/
  @ApiModelProperty(value = "")
  public Boolean isInstalment() {
    return instalment;
  }

  public void setInstalment(Boolean instalment) {
    this.instalment = instalment;
  }

  public TransactionInfo interactionCounter(Integer interactionCounter) {
    this.interactionCounter = interactionCounter;
    return this;
  }

   /**
   * Get interactionCounter
   * @return interactionCounter
  **/
  @ApiModelProperty(value = "")
  public Integer getInteractionCounter() {
    return interactionCounter;
  }

  public void setInteractionCounter(Integer interactionCounter) {
    this.interactionCounter = interactionCounter;
  }

  public TransactionInfo issuerCode(String issuerCode) {
    this.issuerCode = issuerCode;
    return this;
  }

   /**
   * Get issuerCode
   * @return issuerCode
  **/
  @ApiModelProperty(value = "")
  public String getIssuerCode() {
    return issuerCode;
  }

  public void setIssuerCode(String issuerCode) {
    this.issuerCode = issuerCode;
  }

  public TransactionInfo messageCategory(String messageCategory) {
    this.messageCategory = messageCategory;
    return this;
  }

   /**
   * Get messageCategory
   * @return messageCategory
  **/
  @ApiModelProperty(value = "")
  public String getMessageCategory() {
    return messageCategory;
  }

  public void setMessageCategory(String messageCategory) {
    this.messageCategory = messageCategory;
  }

  public TransactionInfo parentTransactionId(String parentTransactionId) {
    this.parentTransactionId = parentTransactionId;
    return this;
  }

   /**
   * Get parentTransactionId
   * @return parentTransactionId
  **/
  @ApiModelProperty(value = "")
  public String getParentTransactionId() {
    return parentTransactionId;
  }

  public void setParentTransactionId(String parentTransactionId) {
    this.parentTransactionId = parentTransactionId;
  }

  public TransactionInfo processingStep(String processingStep) {
    this.processingStep = processingStep;
    return this;
  }

   /**
   * Get processingStep
   * @return processingStep
  **/
  @ApiModelProperty(value = "")
  public String getProcessingStep() {
    return processingStep;
  }

  public void setProcessingStep(String processingStep) {
    this.processingStep = processingStep;
  }

  public TransactionInfo recurring(Boolean recurring) {
    this.recurring = recurring;
    return this;
  }

   /**
   * Get recurring
   * @return recurring
  **/
  @ApiModelProperty(value = "")
  public Boolean isRecurring() {
    return recurring;
  }

  public void setRecurring(Boolean recurring) {
    this.recurring = recurring;
  }

  public TransactionInfo sdkTransactionId(String sdkTransactionId) {
    this.sdkTransactionId = sdkTransactionId;
    return this;
  }

   /**
   * Get sdkTransactionId
   * @return sdkTransactionId
  **/
  @ApiModelProperty(value = "")
  public String getSdkTransactionId() {
    return sdkTransactionId;
  }

  public void setSdkTransactionId(String sdkTransactionId) {
    this.sdkTransactionId = sdkTransactionId;
  }

  public TransactionInfo secureVersion(String secureVersion) {
    this.secureVersion = secureVersion;
    return this;
  }

   /**
   * Get secureVersion
   * @return secureVersion
  **/
  @ApiModelProperty(value = "")
  public String getSecureVersion() {
    return secureVersion;
  }

  public void setSecureVersion(String secureVersion) {
    this.secureVersion = secureVersion;
  }

  public TransactionInfo threedsServerTransactionId(String threedsServerTransactionId) {
    this.threedsServerTransactionId = threedsServerTransactionId;
    return this;
  }

   /**
   * Get threedsServerTransactionId
   * @return threedsServerTransactionId
  **/
  @ApiModelProperty(value = "")
  public String getThreedsServerTransactionId() {
    return threedsServerTransactionId;
  }

  public void setThreedsServerTransactionId(String threedsServerTransactionId) {
    this.threedsServerTransactionId = threedsServerTransactionId;
  }

  public TransactionInfo transactionStatus(String transactionStatus) {
    this.transactionStatus = transactionStatus;
    return this;
  }

   /**
   * Get transactionStatus
   * @return transactionStatus
  **/
  @ApiModelProperty(value = "")
  public String getTransactionStatus() {
    return transactionStatus;
  }

  public void setTransactionStatus(String transactionStatus) {
    this.transactionStatus = transactionStatus;
  }

  public TransactionInfo validationReason(String validationReason) {
    this.validationReason = validationReason;
    return this;
  }

   /**
   * Get validationReason
   * @return validationReason
  **/
  @ApiModelProperty(value = "")
  public String getValidationReason() {
    return validationReason;
  }

  public void setValidationReason(String validationReason) {
    this.validationReason = validationReason;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransactionInfo transactionInfo = (TransactionInfo) o;
    return Objects.equals(this.aav, transactionInfo.aav) &&
        Objects.equals(this.acsMaxChallenges, transactionInfo.acsMaxChallenges) &&
        Objects.equals(this.acsRenderingType, transactionInfo.acsRenderingType) &&
        Objects.equals(this.acsTransactionId, transactionInfo.acsTransactionId) &&
        Objects.equals(this.authenticationMethod, transactionInfo.authenticationMethod) &&
        Objects.equals(this.authenticationName, transactionInfo.authenticationName) &&
        Objects.equals(this.authenticationType, transactionInfo.authenticationType) &&
        Objects.equals(this.binRangeId, transactionInfo.binRangeId) &&
        Objects.equals(this.cRes, transactionInfo.cRes) &&
        Objects.equals(this.completionDate, transactionInfo.completionDate) &&
        Objects.equals(this.creationDate, transactionInfo.creationDate) &&
        Objects.equals(this.currentStepId, transactionInfo.currentStepId) &&
        Objects.equals(this.deviceChannel, transactionInfo.deviceChannel) &&
        Objects.equals(this.dsTransactionId, transactionInfo.dsTransactionId) &&
        Objects.equals(this.dsUrl, transactionInfo.dsUrl) &&
        Objects.equals(this.eci, transactionInfo.eci) &&
        Objects.equals(this.instalment, transactionInfo.instalment) &&
        Objects.equals(this.interactionCounter, transactionInfo.interactionCounter) &&
        Objects.equals(this.issuerCode, transactionInfo.issuerCode) &&
        Objects.equals(this.messageCategory, transactionInfo.messageCategory) &&
        Objects.equals(this.parentTransactionId, transactionInfo.parentTransactionId) &&
        Objects.equals(this.processingStep, transactionInfo.processingStep) &&
        Objects.equals(this.recurring, transactionInfo.recurring) &&
        Objects.equals(this.sdkTransactionId, transactionInfo.sdkTransactionId) &&
        Objects.equals(this.secureVersion, transactionInfo.secureVersion) &&
        Objects.equals(this.threedsServerTransactionId, transactionInfo.threedsServerTransactionId) &&
        Objects.equals(this.transactionStatus, transactionInfo.transactionStatus) &&
        Objects.equals(this.validationReason, transactionInfo.validationReason);
  }

  @Override
  public int hashCode() {
    return Objects.hash(aav, acsMaxChallenges, acsRenderingType, acsTransactionId, authenticationMethod, authenticationName, authenticationType, binRangeId, cRes, completionDate, creationDate, currentStepId, deviceChannel, dsTransactionId, dsUrl, eci, instalment, interactionCounter, issuerCode, messageCategory, parentTransactionId, processingStep, recurring, sdkTransactionId, secureVersion, threedsServerTransactionId, transactionStatus, validationReason);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransactionInfo {\n");
    
    sb.append("    aav: ").append(toIndentedString(aav)).append("\n");
    sb.append("    acsMaxChallenges: ").append(toIndentedString(acsMaxChallenges)).append("\n");
    sb.append("    acsRenderingType: ").append(toIndentedString(acsRenderingType)).append("\n");
    sb.append("    acsTransactionId: ").append(toIndentedString(acsTransactionId)).append("\n");
    sb.append("    authenticationMethod: ").append(toIndentedString(authenticationMethod)).append("\n");
    sb.append("    authenticationName: ").append(toIndentedString(authenticationName)).append("\n");
    sb.append("    authenticationType: ").append(toIndentedString(authenticationType)).append("\n");
    sb.append("    binRangeId: ").append(toIndentedString(binRangeId)).append("\n");
    sb.append("    cRes: ").append(toIndentedString(cRes)).append("\n");
    sb.append("    completionDate: ").append(toIndentedString(completionDate)).append("\n");
    sb.append("    creationDate: ").append(toIndentedString(creationDate)).append("\n");
    sb.append("    currentStepId: ").append(toIndentedString(currentStepId)).append("\n");
    sb.append("    deviceChannel: ").append(toIndentedString(deviceChannel)).append("\n");
    sb.append("    dsTransactionId: ").append(toIndentedString(dsTransactionId)).append("\n");
    sb.append("    dsUrl: ").append(toIndentedString(dsUrl)).append("\n");
    sb.append("    eci: ").append(toIndentedString(eci)).append("\n");
    sb.append("    instalment: ").append(toIndentedString(instalment)).append("\n");
    sb.append("    interactionCounter: ").append(toIndentedString(interactionCounter)).append("\n");
    sb.append("    issuerCode: ").append(toIndentedString(issuerCode)).append("\n");
    sb.append("    messageCategory: ").append(toIndentedString(messageCategory)).append("\n");
    sb.append("    parentTransactionId: ").append(toIndentedString(parentTransactionId)).append("\n");
    sb.append("    processingStep: ").append(toIndentedString(processingStep)).append("\n");
    sb.append("    recurring: ").append(toIndentedString(recurring)).append("\n");
    sb.append("    sdkTransactionId: ").append(toIndentedString(sdkTransactionId)).append("\n");
    sb.append("    secureVersion: ").append(toIndentedString(secureVersion)).append("\n");
    sb.append("    threedsServerTransactionId: ").append(toIndentedString(threedsServerTransactionId)).append("\n");
    sb.append("    transactionStatus: ").append(toIndentedString(transactionStatus)).append("\n");
    sb.append("    validationReason: ").append(toIndentedString(validationReason)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

