/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.opentech.acsemv3dsProxyApiClient.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * TransactionOtherInfo
 */

public class TransactionOtherInfo {
  @JsonProperty("merchantCountryCode")
  private String merchantCountryCode = null;

  @JsonProperty("merchantName")
  private String merchantName = null;

  @JsonProperty("purchaseInstalData")
  private String purchaseInstalData = null;

  @JsonProperty("recurringExpiry")
  private String recurringExpiry = null;

  @JsonProperty("recurringFrequency")
  private String recurringFrequency = null;

  @JsonProperty("threeDSRequestorAuthenticationInd")
  private String threeDSRequestorAuthenticationInd = null;

  @JsonProperty("threeDSRequestorDecMaxTime")
  private String threeDSRequestorDecMaxTime = null;

  @JsonProperty("threeDSRequestorDecReqInd")
  private String threeDSRequestorDecReqInd = null;

  @JsonProperty("threeDSRequestorID")
  private String threeDSRequestorID = null;

  @JsonProperty("threeDSRequestorName")
  private String threeDSRequestorName = null;

  @JsonProperty("threeDSServerRefNumber")
  private String threeDSServerRefNumber = null;

  @JsonProperty("threeRIInd")
  private String threeRIInd = null;

  @JsonProperty("transType")
  private String transType = null;

  public TransactionOtherInfo merchantCountryCode(String merchantCountryCode) {
    this.merchantCountryCode = merchantCountryCode;
    return this;
  }

   /**
   * Get merchantCountryCode
   * @return merchantCountryCode
  **/
  @ApiModelProperty(value = "")
  public String getMerchantCountryCode() {
    return merchantCountryCode;
  }

  public void setMerchantCountryCode(String merchantCountryCode) {
    this.merchantCountryCode = merchantCountryCode;
  }

  public TransactionOtherInfo merchantName(String merchantName) {
    this.merchantName = merchantName;
    return this;
  }

   /**
   * Get merchantName
   * @return merchantName
  **/
  @ApiModelProperty(value = "")
  public String getMerchantName() {
    return merchantName;
  }

  public void setMerchantName(String merchantName) {
    this.merchantName = merchantName;
  }

  public TransactionOtherInfo purchaseInstalData(String purchaseInstalData) {
    this.purchaseInstalData = purchaseInstalData;
    return this;
  }

   /**
   * Get purchaseInstalData
   * @return purchaseInstalData
  **/
  @ApiModelProperty(value = "")
  public String getPurchaseInstalData() {
    return purchaseInstalData;
  }

  public void setPurchaseInstalData(String purchaseInstalData) {
    this.purchaseInstalData = purchaseInstalData;
  }

  public TransactionOtherInfo recurringExpiry(String recurringExpiry) {
    this.recurringExpiry = recurringExpiry;
    return this;
  }

   /**
   * Get recurringExpiry
   * @return recurringExpiry
  **/
  @ApiModelProperty(value = "")
  public String getRecurringExpiry() {
    return recurringExpiry;
  }

  public void setRecurringExpiry(String recurringExpiry) {
    this.recurringExpiry = recurringExpiry;
  }

  public TransactionOtherInfo recurringFrequency(String recurringFrequency) {
    this.recurringFrequency = recurringFrequency;
    return this;
  }

   /**
   * Get recurringFrequency
   * @return recurringFrequency
  **/
  @ApiModelProperty(value = "")
  public String getRecurringFrequency() {
    return recurringFrequency;
  }

  public void setRecurringFrequency(String recurringFrequency) {
    this.recurringFrequency = recurringFrequency;
  }

  public TransactionOtherInfo threeDSRequestorAuthenticationInd(String threeDSRequestorAuthenticationInd) {
    this.threeDSRequestorAuthenticationInd = threeDSRequestorAuthenticationInd;
    return this;
  }

   /**
   * Get threeDSRequestorAuthenticationInd
   * @return threeDSRequestorAuthenticationInd
  **/
  @ApiModelProperty(value = "")
  public String getThreeDSRequestorAuthenticationInd() {
    return threeDSRequestorAuthenticationInd;
  }

  public void setThreeDSRequestorAuthenticationInd(String threeDSRequestorAuthenticationInd) {
    this.threeDSRequestorAuthenticationInd = threeDSRequestorAuthenticationInd;
  }

  public TransactionOtherInfo threeDSRequestorDecMaxTime(String threeDSRequestorDecMaxTime) {
    this.threeDSRequestorDecMaxTime = threeDSRequestorDecMaxTime;
    return this;
  }

   /**
   * Get threeDSRequestorDecMaxTime
   * @return threeDSRequestorDecMaxTime
  **/
  @ApiModelProperty(value = "")
  public String getThreeDSRequestorDecMaxTime() {
    return threeDSRequestorDecMaxTime;
  }

  public void setThreeDSRequestorDecMaxTime(String threeDSRequestorDecMaxTime) {
    this.threeDSRequestorDecMaxTime = threeDSRequestorDecMaxTime;
  }

  public TransactionOtherInfo threeDSRequestorDecReqInd(String threeDSRequestorDecReqInd) {
    this.threeDSRequestorDecReqInd = threeDSRequestorDecReqInd;
    return this;
  }

   /**
   * Get threeDSRequestorDecReqInd
   * @return threeDSRequestorDecReqInd
  **/
  @ApiModelProperty(value = "")
  public String getThreeDSRequestorDecReqInd() {
    return threeDSRequestorDecReqInd;
  }

  public void setThreeDSRequestorDecReqInd(String threeDSRequestorDecReqInd) {
    this.threeDSRequestorDecReqInd = threeDSRequestorDecReqInd;
  }

  public TransactionOtherInfo threeDSRequestorID(String threeDSRequestorID) {
    this.threeDSRequestorID = threeDSRequestorID;
    return this;
  }

   /**
   * Get threeDSRequestorID
   * @return threeDSRequestorID
  **/
  @ApiModelProperty(value = "")
  public String getThreeDSRequestorID() {
    return threeDSRequestorID;
  }

  public void setThreeDSRequestorID(String threeDSRequestorID) {
    this.threeDSRequestorID = threeDSRequestorID;
  }

  public TransactionOtherInfo threeDSRequestorName(String threeDSRequestorName) {
    this.threeDSRequestorName = threeDSRequestorName;
    return this;
  }

   /**
   * Get threeDSRequestorName
   * @return threeDSRequestorName
  **/
  @ApiModelProperty(value = "")
  public String getThreeDSRequestorName() {
    return threeDSRequestorName;
  }

  public void setThreeDSRequestorName(String threeDSRequestorName) {
    this.threeDSRequestorName = threeDSRequestorName;
  }

  public TransactionOtherInfo threeDSServerRefNumber(String threeDSServerRefNumber) {
    this.threeDSServerRefNumber = threeDSServerRefNumber;
    return this;
  }

   /**
   * Get threeDSServerRefNumber
   * @return threeDSServerRefNumber
  **/
  @ApiModelProperty(value = "")
  public String getThreeDSServerRefNumber() {
    return threeDSServerRefNumber;
  }

  public void setThreeDSServerRefNumber(String threeDSServerRefNumber) {
    this.threeDSServerRefNumber = threeDSServerRefNumber;
  }

  public TransactionOtherInfo threeRIInd(String threeRIInd) {
    this.threeRIInd = threeRIInd;
    return this;
  }

   /**
   * Get threeRIInd
   * @return threeRIInd
  **/
  @ApiModelProperty(value = "")
  public String getThreeRIInd() {
    return threeRIInd;
  }

  public void setThreeRIInd(String threeRIInd) {
    this.threeRIInd = threeRIInd;
  }

  public TransactionOtherInfo transType(String transType) {
    this.transType = transType;
    return this;
  }

   /**
   * Get transType
   * @return transType
  **/
  @ApiModelProperty(value = "")
  public String getTransType() {
    return transType;
  }

  public void setTransType(String transType) {
    this.transType = transType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransactionOtherInfo transactionOtherInfo = (TransactionOtherInfo) o;
    return Objects.equals(this.merchantCountryCode, transactionOtherInfo.merchantCountryCode) &&
        Objects.equals(this.merchantName, transactionOtherInfo.merchantName) &&
        Objects.equals(this.purchaseInstalData, transactionOtherInfo.purchaseInstalData) &&
        Objects.equals(this.recurringExpiry, transactionOtherInfo.recurringExpiry) &&
        Objects.equals(this.recurringFrequency, transactionOtherInfo.recurringFrequency) &&
        Objects.equals(this.threeDSRequestorAuthenticationInd, transactionOtherInfo.threeDSRequestorAuthenticationInd) &&
        Objects.equals(this.threeDSRequestorDecMaxTime, transactionOtherInfo.threeDSRequestorDecMaxTime) &&
        Objects.equals(this.threeDSRequestorDecReqInd, transactionOtherInfo.threeDSRequestorDecReqInd) &&
        Objects.equals(this.threeDSRequestorID, transactionOtherInfo.threeDSRequestorID) &&
        Objects.equals(this.threeDSRequestorName, transactionOtherInfo.threeDSRequestorName) &&
        Objects.equals(this.threeDSServerRefNumber, transactionOtherInfo.threeDSServerRefNumber) &&
        Objects.equals(this.threeRIInd, transactionOtherInfo.threeRIInd) &&
        Objects.equals(this.transType, transactionOtherInfo.transType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(merchantCountryCode, merchantName, purchaseInstalData, recurringExpiry, recurringFrequency, threeDSRequestorAuthenticationInd, threeDSRequestorDecMaxTime, threeDSRequestorDecReqInd, threeDSRequestorID, threeDSRequestorName, threeDSServerRefNumber, threeRIInd, transType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransactionOtherInfo {\n");
    
    sb.append("    merchantCountryCode: ").append(toIndentedString(merchantCountryCode)).append("\n");
    sb.append("    merchantName: ").append(toIndentedString(merchantName)).append("\n");
    sb.append("    purchaseInstalData: ").append(toIndentedString(purchaseInstalData)).append("\n");
    sb.append("    recurringExpiry: ").append(toIndentedString(recurringExpiry)).append("\n");
    sb.append("    recurringFrequency: ").append(toIndentedString(recurringFrequency)).append("\n");
    sb.append("    threeDSRequestorAuthenticationInd: ").append(toIndentedString(threeDSRequestorAuthenticationInd)).append("\n");
    sb.append("    threeDSRequestorDecMaxTime: ").append(toIndentedString(threeDSRequestorDecMaxTime)).append("\n");
    sb.append("    threeDSRequestorDecReqInd: ").append(toIndentedString(threeDSRequestorDecReqInd)).append("\n");
    sb.append("    threeDSRequestorID: ").append(toIndentedString(threeDSRequestorID)).append("\n");
    sb.append("    threeDSRequestorName: ").append(toIndentedString(threeDSRequestorName)).append("\n");
    sb.append("    threeDSServerRefNumber: ").append(toIndentedString(threeDSServerRefNumber)).append("\n");
    sb.append("    threeRIInd: ").append(toIndentedString(threeRIInd)).append("\n");
    sb.append("    transType: ").append(toIndentedString(transType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

