/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.opentech.acsemv3dsProxyApiClient.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.opentech.acsemv3dsProxyApiClient.model.ThreeDSAcsRenderingType;
import com.opentech.acsemv3dsProxyApiClient.model.TransactionOtherInfo;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.util.Date;

/**
 * TransactionInfo
 */

public class TransactionInfo {
  @JsonProperty("acquirerBin")
  private String acquirerBin = null;

  @JsonProperty("acquirerMerchantId")
  private String acquirerMerchantId = null;

  @JsonProperty("acsMaxChallenges")
  private Integer acsMaxChallenges = null;

  @JsonProperty("acsRenderingType")
  private ThreeDSAcsRenderingType acsRenderingType = null;

  @JsonProperty("acsTransactionId")
  private String acsTransactionId = null;

  @JsonProperty("amount")
  private BigDecimal amount = null;

  @JsonProperty("authenticationMethod")
  private String authenticationMethod = null;

  @JsonProperty("authenticationName")
  private String authenticationName = null;

  @JsonProperty("authenticationType")
  private String authenticationType = null;

  @JsonProperty("binRangeId")
  private String binRangeId = null;

  @JsonProperty("cRes")
  private byte[] cRes = null;

  @JsonProperty("completionDate")
  private Date completionDate = null;

  @JsonProperty("creationDate")
  private Date creationDate = null;

  @JsonProperty("currencyCode")
  private String currencyCode = null;

  @JsonProperty("currencyExponent")
  private String currencyExponent = null;

  @JsonProperty("currentStepId")
  private String currentStepId = null;

  @JsonProperty("deviceChannel")
  private String deviceChannel = null;

  @JsonProperty("dsTransactionId")
  private String dsTransactionId = null;

  @JsonProperty("dsUrl")
  private String dsUrl = null;

  @JsonProperty("errorCode")
  private String errorCode = null;

  @JsonProperty("errorCodeText")
  private String errorCodeText = null;

  @JsonProperty("errorDescription")
  private String errorDescription = null;

  @JsonProperty("errorDetail")
  private String errorDetail = null;

  @JsonProperty("instalment")
  private Boolean instalment = null;

  @JsonProperty("interactionCounter")
  private Integer interactionCounter = null;

  @JsonProperty("internalTransactionStatus")
  private String internalTransactionStatus = null;

  @JsonProperty("internalTransactionStatusReason")
  private String internalTransactionStatusReason = null;

  @JsonProperty("issuerCode")
  private String issuerCode = null;

  @JsonProperty("messageCategory")
  private String messageCategory = null;

  @JsonProperty("otherInfo")
  private TransactionOtherInfo otherInfo = null;

  @JsonProperty("parentTransactionId")
  private String parentTransactionId = null;

  @JsonProperty("processingStep")
  private String processingStep = null;

  @JsonProperty("purchaseDate")
  private Date purchaseDate = null;

  @JsonProperty("recurring")
  private Boolean recurring = null;

  @JsonProperty("rresResultStatus")
  private String rresResultStatus = null;

  @JsonProperty("sdkMaxTimeout")
  private String sdkMaxTimeout = null;

  @JsonProperty("sdkTransactionId")
  private String sdkTransactionId = null;

  @JsonProperty("secureVersion")
  private String secureVersion = null;

  @JsonProperty("threedsServerTransactionId")
  private String threedsServerTransactionId = null;

  @JsonProperty("transactionStatus")
  private String transactionStatus = null;

  @JsonProperty("transactionStatusReason")
  private String transactionStatusReason = null;

  @JsonProperty("txLanguage")
  private String txLanguage = null;

  public TransactionInfo acquirerBin(String acquirerBin) {
    this.acquirerBin = acquirerBin;
    return this;
  }

   /**
   * Get acquirerBin
   * @return acquirerBin
  **/
  @ApiModelProperty(value = "")
  public String getAcquirerBin() {
    return acquirerBin;
  }

  public void setAcquirerBin(String acquirerBin) {
    this.acquirerBin = acquirerBin;
  }

  public TransactionInfo acquirerMerchantId(String acquirerMerchantId) {
    this.acquirerMerchantId = acquirerMerchantId;
    return this;
  }

   /**
   * Get acquirerMerchantId
   * @return acquirerMerchantId
  **/
  @ApiModelProperty(value = "")
  public String getAcquirerMerchantId() {
    return acquirerMerchantId;
  }

  public void setAcquirerMerchantId(String acquirerMerchantId) {
    this.acquirerMerchantId = acquirerMerchantId;
  }

  public TransactionInfo acsMaxChallenges(Integer acsMaxChallenges) {
    this.acsMaxChallenges = acsMaxChallenges;
    return this;
  }

   /**
   * Get acsMaxChallenges
   * @return acsMaxChallenges
  **/
  @ApiModelProperty(value = "")
  public Integer getAcsMaxChallenges() {
    return acsMaxChallenges;
  }

  public void setAcsMaxChallenges(Integer acsMaxChallenges) {
    this.acsMaxChallenges = acsMaxChallenges;
  }

  public TransactionInfo acsRenderingType(ThreeDSAcsRenderingType acsRenderingType) {
    this.acsRenderingType = acsRenderingType;
    return this;
  }

   /**
   * Get acsRenderingType
   * @return acsRenderingType
  **/
  @ApiModelProperty(value = "")
  public ThreeDSAcsRenderingType getAcsRenderingType() {
    return acsRenderingType;
  }

  public void setAcsRenderingType(ThreeDSAcsRenderingType acsRenderingType) {
    this.acsRenderingType = acsRenderingType;
  }

  public TransactionInfo acsTransactionId(String acsTransactionId) {
    this.acsTransactionId = acsTransactionId;
    return this;
  }

   /**
   * Get acsTransactionId
   * @return acsTransactionId
  **/
  @ApiModelProperty(value = "")
  public String getAcsTransactionId() {
    return acsTransactionId;
  }

  public void setAcsTransactionId(String acsTransactionId) {
    this.acsTransactionId = acsTransactionId;
  }

  public TransactionInfo amount(BigDecimal amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getAmount() {
    return amount;
  }

  public void setAmount(BigDecimal amount) {
    this.amount = amount;
  }

  public TransactionInfo authenticationMethod(String authenticationMethod) {
    this.authenticationMethod = authenticationMethod;
    return this;
  }

   /**
   * Get authenticationMethod
   * @return authenticationMethod
  **/
  @ApiModelProperty(value = "")
  public String getAuthenticationMethod() {
    return authenticationMethod;
  }

  public void setAuthenticationMethod(String authenticationMethod) {
    this.authenticationMethod = authenticationMethod;
  }

  public TransactionInfo authenticationName(String authenticationName) {
    this.authenticationName = authenticationName;
    return this;
  }

   /**
   * Get authenticationName
   * @return authenticationName
  **/
  @ApiModelProperty(value = "")
  public String getAuthenticationName() {
    return authenticationName;
  }

  public void setAuthenticationName(String authenticationName) {
    this.authenticationName = authenticationName;
  }

  public TransactionInfo authenticationType(String authenticationType) {
    this.authenticationType = authenticationType;
    return this;
  }

   /**
   * Get authenticationType
   * @return authenticationType
  **/
  @ApiModelProperty(value = "")
  public String getAuthenticationType() {
    return authenticationType;
  }

  public void setAuthenticationType(String authenticationType) {
    this.authenticationType = authenticationType;
  }

  public TransactionInfo binRangeId(String binRangeId) {
    this.binRangeId = binRangeId;
    return this;
  }

   /**
   * Get binRangeId
   * @return binRangeId
  **/
  @ApiModelProperty(value = "")
  public String getBinRangeId() {
    return binRangeId;
  }

  public void setBinRangeId(String binRangeId) {
    this.binRangeId = binRangeId;
  }

  public TransactionInfo cRes(byte[] cRes) {
    this.cRes = cRes;
    return this;
  }

   /**
   * Get cRes
   * @return cRes
  **/
  @ApiModelProperty(value = "")
  public byte[] getCRes() {
    return cRes;
  }

  public void setCRes(byte[] cRes) {
    this.cRes = cRes;
  }

  public TransactionInfo completionDate(Date completionDate) {
    this.completionDate = completionDate;
    return this;
  }

   /**
   * Get completionDate
   * @return completionDate
  **/
  @ApiModelProperty(value = "")
  public Date getCompletionDate() {
    return completionDate;
  }

  public void setCompletionDate(Date completionDate) {
    this.completionDate = completionDate;
  }

  public TransactionInfo creationDate(Date creationDate) {
    this.creationDate = creationDate;
    return this;
  }

   /**
   * Get creationDate
   * @return creationDate
  **/
  @ApiModelProperty(value = "")
  public Date getCreationDate() {
    return creationDate;
  }

  public void setCreationDate(Date creationDate) {
    this.creationDate = creationDate;
  }

  public TransactionInfo currencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
    return this;
  }

   /**
   * Get currencyCode
   * @return currencyCode
  **/
  @ApiModelProperty(value = "")
  public String getCurrencyCode() {
    return currencyCode;
  }

  public void setCurrencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
  }

  public TransactionInfo currencyExponent(String currencyExponent) {
    this.currencyExponent = currencyExponent;
    return this;
  }

   /**
   * Get currencyExponent
   * @return currencyExponent
  **/
  @ApiModelProperty(value = "")
  public String getCurrencyExponent() {
    return currencyExponent;
  }

  public void setCurrencyExponent(String currencyExponent) {
    this.currencyExponent = currencyExponent;
  }

  public TransactionInfo currentStepId(String currentStepId) {
    this.currentStepId = currentStepId;
    return this;
  }

   /**
   * Get currentStepId
   * @return currentStepId
  **/
  @ApiModelProperty(value = "")
  public String getCurrentStepId() {
    return currentStepId;
  }

  public void setCurrentStepId(String currentStepId) {
    this.currentStepId = currentStepId;
  }

  public TransactionInfo deviceChannel(String deviceChannel) {
    this.deviceChannel = deviceChannel;
    return this;
  }

   /**
   * Get deviceChannel
   * @return deviceChannel
  **/
  @ApiModelProperty(value = "")
  public String getDeviceChannel() {
    return deviceChannel;
  }

  public void setDeviceChannel(String deviceChannel) {
    this.deviceChannel = deviceChannel;
  }

  public TransactionInfo dsTransactionId(String dsTransactionId) {
    this.dsTransactionId = dsTransactionId;
    return this;
  }

   /**
   * Get dsTransactionId
   * @return dsTransactionId
  **/
  @ApiModelProperty(value = "")
  public String getDsTransactionId() {
    return dsTransactionId;
  }

  public void setDsTransactionId(String dsTransactionId) {
    this.dsTransactionId = dsTransactionId;
  }

  public TransactionInfo dsUrl(String dsUrl) {
    this.dsUrl = dsUrl;
    return this;
  }

   /**
   * Get dsUrl
   * @return dsUrl
  **/
  @ApiModelProperty(value = "")
  public String getDsUrl() {
    return dsUrl;
  }

  public void setDsUrl(String dsUrl) {
    this.dsUrl = dsUrl;
  }

  public TransactionInfo errorCode(String errorCode) {
    this.errorCode = errorCode;
    return this;
  }

   /**
   * Get errorCode
   * @return errorCode
  **/
  @ApiModelProperty(value = "")
  public String getErrorCode() {
    return errorCode;
  }

  public void setErrorCode(String errorCode) {
    this.errorCode = errorCode;
  }

  public TransactionInfo errorCodeText(String errorCodeText) {
    this.errorCodeText = errorCodeText;
    return this;
  }

   /**
   * Get errorCodeText
   * @return errorCodeText
  **/
  @ApiModelProperty(value = "")
  public String getErrorCodeText() {
    return errorCodeText;
  }

  public void setErrorCodeText(String errorCodeText) {
    this.errorCodeText = errorCodeText;
  }

  public TransactionInfo errorDescription(String errorDescription) {
    this.errorDescription = errorDescription;
    return this;
  }

   /**
   * Get errorDescription
   * @return errorDescription
  **/
  @ApiModelProperty(value = "")
  public String getErrorDescription() {
    return errorDescription;
  }

  public void setErrorDescription(String errorDescription) {
    this.errorDescription = errorDescription;
  }

  public TransactionInfo errorDetail(String errorDetail) {
    this.errorDetail = errorDetail;
    return this;
  }

   /**
   * Get errorDetail
   * @return errorDetail
  **/
  @ApiModelProperty(value = "")
  public String getErrorDetail() {
    return errorDetail;
  }

  public void setErrorDetail(String errorDetail) {
    this.errorDetail = errorDetail;
  }

  public TransactionInfo instalment(Boolean instalment) {
    this.instalment = instalment;
    return this;
  }

   /**
   * Get instalment
   * @return instalment
  **/
  @ApiModelProperty(value = "")
  public Boolean isInstalment() {
    return instalment;
  }

  public void setInstalment(Boolean instalment) {
    this.instalment = instalment;
  }

  public TransactionInfo interactionCounter(Integer interactionCounter) {
    this.interactionCounter = interactionCounter;
    return this;
  }

   /**
   * Get interactionCounter
   * @return interactionCounter
  **/
  @ApiModelProperty(value = "")
  public Integer getInteractionCounter() {
    return interactionCounter;
  }

  public void setInteractionCounter(Integer interactionCounter) {
    this.interactionCounter = interactionCounter;
  }

  public TransactionInfo internalTransactionStatus(String internalTransactionStatus) {
    this.internalTransactionStatus = internalTransactionStatus;
    return this;
  }

   /**
   * Get internalTransactionStatus
   * @return internalTransactionStatus
  **/
  @ApiModelProperty(value = "")
  public String getInternalTransactionStatus() {
    return internalTransactionStatus;
  }

  public void setInternalTransactionStatus(String internalTransactionStatus) {
    this.internalTransactionStatus = internalTransactionStatus;
  }

  public TransactionInfo internalTransactionStatusReason(String internalTransactionStatusReason) {
    this.internalTransactionStatusReason = internalTransactionStatusReason;
    return this;
  }

   /**
   * Get internalTransactionStatusReason
   * @return internalTransactionStatusReason
  **/
  @ApiModelProperty(value = "")
  public String getInternalTransactionStatusReason() {
    return internalTransactionStatusReason;
  }

  public void setInternalTransactionStatusReason(String internalTransactionStatusReason) {
    this.internalTransactionStatusReason = internalTransactionStatusReason;
  }

  public TransactionInfo issuerCode(String issuerCode) {
    this.issuerCode = issuerCode;
    return this;
  }

   /**
   * Get issuerCode
   * @return issuerCode
  **/
  @ApiModelProperty(value = "")
  public String getIssuerCode() {
    return issuerCode;
  }

  public void setIssuerCode(String issuerCode) {
    this.issuerCode = issuerCode;
  }

  public TransactionInfo messageCategory(String messageCategory) {
    this.messageCategory = messageCategory;
    return this;
  }

   /**
   * Get messageCategory
   * @return messageCategory
  **/
  @ApiModelProperty(value = "")
  public String getMessageCategory() {
    return messageCategory;
  }

  public void setMessageCategory(String messageCategory) {
    this.messageCategory = messageCategory;
  }

  public TransactionInfo otherInfo(TransactionOtherInfo otherInfo) {
    this.otherInfo = otherInfo;
    return this;
  }

   /**
   * Get otherInfo
   * @return otherInfo
  **/
  @ApiModelProperty(value = "")
  public TransactionOtherInfo getOtherInfo() {
    return otherInfo;
  }

  public void setOtherInfo(TransactionOtherInfo otherInfo) {
    this.otherInfo = otherInfo;
  }

  public TransactionInfo parentTransactionId(String parentTransactionId) {
    this.parentTransactionId = parentTransactionId;
    return this;
  }

   /**
   * Get parentTransactionId
   * @return parentTransactionId
  **/
  @ApiModelProperty(value = "")
  public String getParentTransactionId() {
    return parentTransactionId;
  }

  public void setParentTransactionId(String parentTransactionId) {
    this.parentTransactionId = parentTransactionId;
  }

  public TransactionInfo processingStep(String processingStep) {
    this.processingStep = processingStep;
    return this;
  }

   /**
   * Get processingStep
   * @return processingStep
  **/
  @ApiModelProperty(value = "")
  public String getProcessingStep() {
    return processingStep;
  }

  public void setProcessingStep(String processingStep) {
    this.processingStep = processingStep;
  }

  public TransactionInfo purchaseDate(Date purchaseDate) {
    this.purchaseDate = purchaseDate;
    return this;
  }

   /**
   * Get purchaseDate
   * @return purchaseDate
  **/
  @ApiModelProperty(value = "")
  public Date getPurchaseDate() {
    return purchaseDate;
  }

  public void setPurchaseDate(Date purchaseDate) {
    this.purchaseDate = purchaseDate;
  }

  public TransactionInfo recurring(Boolean recurring) {
    this.recurring = recurring;
    return this;
  }

   /**
   * Get recurring
   * @return recurring
  **/
  @ApiModelProperty(value = "")
  public Boolean isRecurring() {
    return recurring;
  }

  public void setRecurring(Boolean recurring) {
    this.recurring = recurring;
  }

  public TransactionInfo rresResultStatus(String rresResultStatus) {
    this.rresResultStatus = rresResultStatus;
    return this;
  }

   /**
   * Get rresResultStatus
   * @return rresResultStatus
  **/
  @ApiModelProperty(value = "")
  public String getRresResultStatus() {
    return rresResultStatus;
  }

  public void setRresResultStatus(String rresResultStatus) {
    this.rresResultStatus = rresResultStatus;
  }

  public TransactionInfo sdkMaxTimeout(String sdkMaxTimeout) {
    this.sdkMaxTimeout = sdkMaxTimeout;
    return this;
  }

   /**
   * Get sdkMaxTimeout
   * @return sdkMaxTimeout
  **/
  @ApiModelProperty(value = "")
  public String getSdkMaxTimeout() {
    return sdkMaxTimeout;
  }

  public void setSdkMaxTimeout(String sdkMaxTimeout) {
    this.sdkMaxTimeout = sdkMaxTimeout;
  }

  public TransactionInfo sdkTransactionId(String sdkTransactionId) {
    this.sdkTransactionId = sdkTransactionId;
    return this;
  }

   /**
   * Get sdkTransactionId
   * @return sdkTransactionId
  **/
  @ApiModelProperty(value = "")
  public String getSdkTransactionId() {
    return sdkTransactionId;
  }

  public void setSdkTransactionId(String sdkTransactionId) {
    this.sdkTransactionId = sdkTransactionId;
  }

  public TransactionInfo secureVersion(String secureVersion) {
    this.secureVersion = secureVersion;
    return this;
  }

   /**
   * Get secureVersion
   * @return secureVersion
  **/
  @ApiModelProperty(value = "")
  public String getSecureVersion() {
    return secureVersion;
  }

  public void setSecureVersion(String secureVersion) {
    this.secureVersion = secureVersion;
  }

  public TransactionInfo threedsServerTransactionId(String threedsServerTransactionId) {
    this.threedsServerTransactionId = threedsServerTransactionId;
    return this;
  }

   /**
   * Get threedsServerTransactionId
   * @return threedsServerTransactionId
  **/
  @ApiModelProperty(value = "")
  public String getThreedsServerTransactionId() {
    return threedsServerTransactionId;
  }

  public void setThreedsServerTransactionId(String threedsServerTransactionId) {
    this.threedsServerTransactionId = threedsServerTransactionId;
  }

  public TransactionInfo transactionStatus(String transactionStatus) {
    this.transactionStatus = transactionStatus;
    return this;
  }

   /**
   * Get transactionStatus
   * @return transactionStatus
  **/
  @ApiModelProperty(value = "")
  public String getTransactionStatus() {
    return transactionStatus;
  }

  public void setTransactionStatus(String transactionStatus) {
    this.transactionStatus = transactionStatus;
  }

  public TransactionInfo transactionStatusReason(String transactionStatusReason) {
    this.transactionStatusReason = transactionStatusReason;
    return this;
  }

   /**
   * Get transactionStatusReason
   * @return transactionStatusReason
  **/
  @ApiModelProperty(value = "")
  public String getTransactionStatusReason() {
    return transactionStatusReason;
  }

  public void setTransactionStatusReason(String transactionStatusReason) {
    this.transactionStatusReason = transactionStatusReason;
  }

  public TransactionInfo txLanguage(String txLanguage) {
    this.txLanguage = txLanguage;
    return this;
  }

   /**
   * Get txLanguage
   * @return txLanguage
  **/
  @ApiModelProperty(value = "")
  public String getTxLanguage() {
    return txLanguage;
  }

  public void setTxLanguage(String txLanguage) {
    this.txLanguage = txLanguage;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransactionInfo transactionInfo = (TransactionInfo) o;
    return Objects.equals(this.acquirerBin, transactionInfo.acquirerBin) &&
        Objects.equals(this.acquirerMerchantId, transactionInfo.acquirerMerchantId) &&
        Objects.equals(this.acsMaxChallenges, transactionInfo.acsMaxChallenges) &&
        Objects.equals(this.acsRenderingType, transactionInfo.acsRenderingType) &&
        Objects.equals(this.acsTransactionId, transactionInfo.acsTransactionId) &&
        Objects.equals(this.amount, transactionInfo.amount) &&
        Objects.equals(this.authenticationMethod, transactionInfo.authenticationMethod) &&
        Objects.equals(this.authenticationName, transactionInfo.authenticationName) &&
        Objects.equals(this.authenticationType, transactionInfo.authenticationType) &&
        Objects.equals(this.binRangeId, transactionInfo.binRangeId) &&
        Objects.equals(this.cRes, transactionInfo.cRes) &&
        Objects.equals(this.completionDate, transactionInfo.completionDate) &&
        Objects.equals(this.creationDate, transactionInfo.creationDate) &&
        Objects.equals(this.currencyCode, transactionInfo.currencyCode) &&
        Objects.equals(this.currencyExponent, transactionInfo.currencyExponent) &&
        Objects.equals(this.currentStepId, transactionInfo.currentStepId) &&
        Objects.equals(this.deviceChannel, transactionInfo.deviceChannel) &&
        Objects.equals(this.dsTransactionId, transactionInfo.dsTransactionId) &&
        Objects.equals(this.dsUrl, transactionInfo.dsUrl) &&
        Objects.equals(this.errorCode, transactionInfo.errorCode) &&
        Objects.equals(this.errorCodeText, transactionInfo.errorCodeText) &&
        Objects.equals(this.errorDescription, transactionInfo.errorDescription) &&
        Objects.equals(this.errorDetail, transactionInfo.errorDetail) &&
        Objects.equals(this.instalment, transactionInfo.instalment) &&
        Objects.equals(this.interactionCounter, transactionInfo.interactionCounter) &&
        Objects.equals(this.internalTransactionStatus, transactionInfo.internalTransactionStatus) &&
        Objects.equals(this.internalTransactionStatusReason, transactionInfo.internalTransactionStatusReason) &&
        Objects.equals(this.issuerCode, transactionInfo.issuerCode) &&
        Objects.equals(this.messageCategory, transactionInfo.messageCategory) &&
        Objects.equals(this.otherInfo, transactionInfo.otherInfo) &&
        Objects.equals(this.parentTransactionId, transactionInfo.parentTransactionId) &&
        Objects.equals(this.processingStep, transactionInfo.processingStep) &&
        Objects.equals(this.purchaseDate, transactionInfo.purchaseDate) &&
        Objects.equals(this.recurring, transactionInfo.recurring) &&
        Objects.equals(this.rresResultStatus, transactionInfo.rresResultStatus) &&
        Objects.equals(this.sdkMaxTimeout, transactionInfo.sdkMaxTimeout) &&
        Objects.equals(this.sdkTransactionId, transactionInfo.sdkTransactionId) &&
        Objects.equals(this.secureVersion, transactionInfo.secureVersion) &&
        Objects.equals(this.threedsServerTransactionId, transactionInfo.threedsServerTransactionId) &&
        Objects.equals(this.transactionStatus, transactionInfo.transactionStatus) &&
        Objects.equals(this.transactionStatusReason, transactionInfo.transactionStatusReason) &&
        Objects.equals(this.txLanguage, transactionInfo.txLanguage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(acquirerBin, acquirerMerchantId, acsMaxChallenges, acsRenderingType, acsTransactionId, amount, authenticationMethod, authenticationName, authenticationType, binRangeId, cRes, completionDate, creationDate, currencyCode, currencyExponent, currentStepId, deviceChannel, dsTransactionId, dsUrl, errorCode, errorCodeText, errorDescription, errorDetail, instalment, interactionCounter, internalTransactionStatus, internalTransactionStatusReason, issuerCode, messageCategory, otherInfo, parentTransactionId, processingStep, purchaseDate, recurring, rresResultStatus, sdkMaxTimeout, sdkTransactionId, secureVersion, threedsServerTransactionId, transactionStatus, transactionStatusReason, txLanguage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransactionInfo {\n");
    
    sb.append("    acquirerBin: ").append(toIndentedString(acquirerBin)).append("\n");
    sb.append("    acquirerMerchantId: ").append(toIndentedString(acquirerMerchantId)).append("\n");
    sb.append("    acsMaxChallenges: ").append(toIndentedString(acsMaxChallenges)).append("\n");
    sb.append("    acsRenderingType: ").append(toIndentedString(acsRenderingType)).append("\n");
    sb.append("    acsTransactionId: ").append(toIndentedString(acsTransactionId)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    authenticationMethod: ").append(toIndentedString(authenticationMethod)).append("\n");
    sb.append("    authenticationName: ").append(toIndentedString(authenticationName)).append("\n");
    sb.append("    authenticationType: ").append(toIndentedString(authenticationType)).append("\n");
    sb.append("    binRangeId: ").append(toIndentedString(binRangeId)).append("\n");
    sb.append("    cRes: ").append(toIndentedString(cRes)).append("\n");
    sb.append("    completionDate: ").append(toIndentedString(completionDate)).append("\n");
    sb.append("    creationDate: ").append(toIndentedString(creationDate)).append("\n");
    sb.append("    currencyCode: ").append(toIndentedString(currencyCode)).append("\n");
    sb.append("    currencyExponent: ").append(toIndentedString(currencyExponent)).append("\n");
    sb.append("    currentStepId: ").append(toIndentedString(currentStepId)).append("\n");
    sb.append("    deviceChannel: ").append(toIndentedString(deviceChannel)).append("\n");
    sb.append("    dsTransactionId: ").append(toIndentedString(dsTransactionId)).append("\n");
    sb.append("    dsUrl: ").append(toIndentedString(dsUrl)).append("\n");
    sb.append("    errorCode: ").append(toIndentedString(errorCode)).append("\n");
    sb.append("    errorCodeText: ").append(toIndentedString(errorCodeText)).append("\n");
    sb.append("    errorDescription: ").append(toIndentedString(errorDescription)).append("\n");
    sb.append("    errorDetail: ").append(toIndentedString(errorDetail)).append("\n");
    sb.append("    instalment: ").append(toIndentedString(instalment)).append("\n");
    sb.append("    interactionCounter: ").append(toIndentedString(interactionCounter)).append("\n");
    sb.append("    internalTransactionStatus: ").append(toIndentedString(internalTransactionStatus)).append("\n");
    sb.append("    internalTransactionStatusReason: ").append(toIndentedString(internalTransactionStatusReason)).append("\n");
    sb.append("    issuerCode: ").append(toIndentedString(issuerCode)).append("\n");
    sb.append("    messageCategory: ").append(toIndentedString(messageCategory)).append("\n");
    sb.append("    otherInfo: ").append(toIndentedString(otherInfo)).append("\n");
    sb.append("    parentTransactionId: ").append(toIndentedString(parentTransactionId)).append("\n");
    sb.append("    processingStep: ").append(toIndentedString(processingStep)).append("\n");
    sb.append("    purchaseDate: ").append(toIndentedString(purchaseDate)).append("\n");
    sb.append("    recurring: ").append(toIndentedString(recurring)).append("\n");
    sb.append("    rresResultStatus: ").append(toIndentedString(rresResultStatus)).append("\n");
    sb.append("    sdkMaxTimeout: ").append(toIndentedString(sdkMaxTimeout)).append("\n");
    sb.append("    sdkTransactionId: ").append(toIndentedString(sdkTransactionId)).append("\n");
    sb.append("    secureVersion: ").append(toIndentedString(secureVersion)).append("\n");
    sb.append("    threedsServerTransactionId: ").append(toIndentedString(threedsServerTransactionId)).append("\n");
    sb.append("    transactionStatus: ").append(toIndentedString(transactionStatus)).append("\n");
    sb.append("    transactionStatusReason: ").append(toIndentedString(transactionStatusReason)).append("\n");
    sb.append("    txLanguage: ").append(toIndentedString(txLanguage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

